/*
 * xiom.ozz amalgamation template -- entries in dependency order.
 * Generated by the upstream-style combine.py; see SPEC.md for provenance.
 */
#include "base/memory/allocator.cc"
#include "base/platform.cc"
#include "base/log.cc"
#include "base/containers/string_archive.cc"
#include "base/encode/group_varint.cc"
#include "base/io/archive.cc"
#include "base/io/stream.cc"
#include "base/maths/simd_math.cc"
#include "base/maths/math_archive.cc"
#include "base/maths/simd_math_archive.cc"
#include "base/maths/soa_math_archive.cc"
#include "base/maths/box.cc"

#include "animation/runtime/animation.cc"
#include "animation/runtime/animation_utils.cc"
#include "animation/runtime/skeleton.cc"
#include "animation/runtime/skeleton_utils.cc"
#include "animation/runtime/sampling_job.cc"
#include "animation/runtime/local_to_model_job.cc"
#include "animation/runtime/blending_job.cc"
#include "animation/runtime/motion_blending_job.cc"
#include "animation/runtime/track.cc"
#include "animation/runtime/track_sampling_job.cc"
#include "animation/runtime/track_triggering_job.cc"
#include "animation/runtime/ik_aim_job.cc"
#include "animation/runtime/ik_two_bone_job.cc"

#include "animation/offline/raw_skeleton.cc"
#include "animation/offline/skeleton_builder.cc"
