// XIOM -- xiom.bitcoin conformance tests (20 checks)
// Copyright (c) 2026 Eleftherios Notas and The XIOM Authors
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Covers the documented API with synthetic buffers built in-test:
// CompactSize boundaries and canonicality, legacy varints, varstr, reader
// bounds, message framing (magic, command padding, payload cap, checksum
// kept raw), version/verack/addr/inv/getdata structures, legacy and SegWit
// transactions with round-trip writes, the genesis block header and
// coinbase walk, script push parsing and template classification, Base58
// (leading zeros, mainnet address round-trip, invalid alphabet) and
// Bech32/Bech32m including the pinned BIP-173/BIP-350 vectors.
//
// Vector provenance: the byte buffers were generated by an independent
// reference implementation (Python) outside the module and cross-checked
// structurally; the Bech32/Bech32m strings are the pinned BIP-173 and
// BIP-350 test vectors, also cross-checked against a reference polymod.
// The Base58 vector is the Bitcoin genesis address
// 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa, whose raw decoded bytes were
// verified independently.
//
// Harness style mirrors xiom.hello / xiom.bencode: one fn tN() -> TestResult
// per check, called directly from main; main prints [PASS]/[FAIL] and
// returns the failure count. All Str equality goes through str_compare
// (BUG 17 discipline: `==` on Str values read from a Vec lowers to a
// pointer comparison).

module bitcoin_tests
use xiom.io; use xiom.test;
use xiom.string; use xiom.string.compare;
use xiom.encoding.hex;
use xiom.bitcoin;

// --------------------------------------------------
//  Test helpers
// --------------------------------------------------

fn streq(a: Str, b: Str) -> Bool {
  return str_compare(a, b) == 0;
}

// Expected bytes for a hex string ("" on malformed input; the test then
// fails on the byte comparison).
fn hb(h: Str) -> Vec[UInt8] {
  let r = hex.hex_decode(h);
  if !r.is_ok {
    return Vec[UInt8].new();
  }
  let v: Vec[UInt8] = r.value;
  return v;
}

fn bytes_equal(a: Vec[UInt8], b: Vec[UInt8]) -> Bool {
  if a.len() != b.len() {
    return false;
  }
  var i = 0;
  while i < a.len() {
    let x: UInt8 = a[i];
    let y: UInt8 = b[i];
    if ((x as Int) & 0xFF) != ((y as Int) & 0xFF) {
      return false;
    }
    i = i + 1;
  }
  return true;
}

fn concat(a: Vec[UInt8], b: Vec[UInt8]) -> Vec[UInt8] {
  var v = Vec[UInt8].new();
  var i = 0;
  while i < a.len() {
    v.push(a[i]);
    i = i + 1;
  }
  var j = 0;
  while j < b.len() {
    v.push(b[j]);
    j = j + 1;
  }
  return v;
}

// First `n` bytes of `a`.
fn prefix_of(a: Vec[UInt8], n: Int) -> Vec[UInt8] {
  var v = Vec[UInt8].new();
  var i = 0;
  while i < n && i < a.len() {
    v.push(a[i]);
    i = i + 1;
  }
  return v;
}

// `n` copies of byte value `b` (0..255).
fn rep_byte(b: Int, n: Int) -> Vec[UInt8] {
  var v = Vec[UInt8].new();
  var i = 0;
  while i < n {
    v.push(b as UInt8);
    i = i + 1;
  }
  return v;
}

fn zeros(n: Int) -> Vec[UInt8] {
  return rep_byte(0, n);
}

// Bytes of a Str, byte-for-byte.
fn ascii(s: Str) -> Vec[UInt8] {
  var v = Vec[UInt8].new();
  let n = string.str_len(s);
  var i = 0;
  while i < n {
    let b: UInt8 = string.byte_at(s, i);
    v.push(b);
    i = i + 1;
  }
  return v;
}

fn u32le(v: Int) -> Vec[UInt8] {
  var o = Vec[UInt8].new();
  o.push((v % 256) as UInt8);
  o.push(((v / 256) % 256) as UInt8);
  o.push(((v / 65536) % 256) as UInt8);
  o.push(((v / 16777216) % 256) as UInt8);
  return o;
}

fn u32be(v: Int) -> Vec[UInt8] {
  var o = Vec[UInt8].new();
  o.push(((v / 16777216) % 256) as UInt8);
  o.push(((v / 65536) % 256) as UInt8);
  o.push(((v / 256) % 256) as UInt8);
  o.push((v % 256) as UInt8);
  return o;
}

// CompactSize-encode with the module writer (round-trip helper).
fn cs_enc(n: Int) -> Vec[UInt8] {
  var o = Vec[UInt8].new();
  compact_size_write(&mut o, n);
  return o;
}

fn cs_dec(data: Vec[UInt8]) -> Result[Int, Str] {
  var r = reader_new(data);
  return compact_size_read(&mut r);
}

fn var_dec(data: Vec[UInt8]) -> Result[Int, Str] {
  var r = reader_new(data);
  return varint_legacy_read(&mut r);
}

fn cs_ok_is(data: Vec[UInt8], want: Int) -> Bool {
  let r = cs_dec(data);
  if !r.is_ok {
    return false;
  }
  let v: Int = r.value;
  return v == want;
}

fn bytes_err(r: Result[Vec[UInt8], Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn int_err(r: Result[Int, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn ints_err(r: Result[Vec[Int], Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn str_err(r: Result[Str, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn header_err(r: Result[MessageHeader, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn version_err(r: Result[VersionMessage, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn addrs_err(r: Result[AddressList, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn inv_err(r: Result[InvList, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn tx_err(r: Result[Tx, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn bh_err(r: Result[BlockHeader, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn block_err(r: Result[Block, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn script_err(r: Result[ScriptDoc, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn bech32_err(r: Result[Bech32Data, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

fn segwit_err(r: Result[SegwitAddress, Str]) -> Str {
  if r.is_ok {
    return "(ok)";
  }
  return r.error;
}

// --------------------------------------------------
//  Pinned synthetic buffers (see the header)
// --------------------------------------------------

fn legacy_tx_bytes() -> Vec[UInt8] {
  var b = hb("0200000001000102030405060708090a0b0c0d0e0f101112131415161718191a");
  b = concat(b, hb("1b1c1d1e1f000000001976a91411111111111111111111111111111111111111"));
  b = concat(b, hb("1188acfeffffff0200f2052a010000001976a914111111111111111111111111"));
  b = concat(b, hb("111111111111111188ace803000000000000066a04deadbeef0f000000"));
  return b;
}

fn segwit_tx_bytes() -> Vec[UInt8] {
  var b = hb("02000000000101ffffffffffffffffffffffffffffffffffffffffffffffffff");
  b = concat(b, hb("ffffffffffffffffffffff00ffffffff02a08601000000000016001422222222"));
  b = concat(b, hb("222222222222222222222222222222220000000000000000016a0203aabbcc21"));
  b = concat(b, hb("0344444444444444444444444444444444444444444444444444444444444444"));
  b = concat(b, hb("4400000000"));
  return b;
}

fn version_bytes() -> Vec[UInt8] {
  var b = hb("7f110100090000000000000029ab5f4900000000000000000000000000000000");
  b = concat(b, hb("000000000000000000000000208d010000000000000000000000000000000000"));
  b = concat(b, hb("ffff0a000001208e08070605040302010c2f78696f6d3a302e312e302f00350c"));
  b = concat(b, hb("0001"));
  return b;
}

fn version_no_relay_bytes() -> Vec[UInt8] {
  var b = hb("7f110100090000000000000029ab5f4900000000000000000000000000000000");
  b = concat(b, hb("000000000000000000000000208d010000000000000000000000000000000000"));
  b = concat(b, hb("ffff0a000001208e08070605040302010c2f78696f6d3a302e312e302f00350c"));
  b = concat(b, hb("00"));
  return b;
}

fn addr_bytes() -> Vec[UInt8] {
  var b = hb("fd020029ab5f49010000000000000000000000000000000000ffff7f00000120");
  b = concat(b, hb("8d00000000000000000000000020010db8000000000000000000000001479d"));
  return b;
}

fn inv_bytes() -> Vec[UInt8] {
  var b = hb("0201000000ababababababababababababababababababababababababababab");
  b = concat(b, hb("ababababab02000000cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"));
  b = concat(b, hb("cdcdcdcdcdcdcdcdcd"));
  return b;
}

fn gen_header_bytes() -> Vec[UInt8] {
  var b = hb("0100000000000000000000000000000000000000000000000000000000000000");
  b = concat(b, hb("000000003ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa"));
  b = concat(b, hb("4b1e5e4a29ab5f49ffff001d1dac2b7c"));
  return b;
}

fn coinbase_bytes() -> Vec[UInt8] {
  var b = hb("0100000001000000000000000000000000000000000000000000000000000000");
  b = concat(b, hb("0000000000ffffffff4d04ffff001d0104455468652054696d65732030332f4a"));
  b = concat(b, hb("616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f662073"));
  b = concat(b, hb("65636f6e64206261696c6f757420666f722062616e6b73ffffffff0100f2052a"));
  b = concat(b, hb("01000000434104678afdb0fe5548271967f1a67130b7105cd6a828e03909a679"));
  b = concat(b, hb("62e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a"));
  b = concat(b, hb("4c702b6bf11d5fac00000000"));
  return b;
}

fn gen_block_bytes() -> Vec[UInt8] {
  var b = gen_header_bytes();
  b = concat(b, hb("01"));
  b = concat(b, coinbase_bytes());
  return b;
}

// A mainnet frame built by hand: magic, command (NUL-padded to 12), u32 LE
// payload length, 4 raw checksum bytes, payload.
fn frame_of(cmd: Str, payload: Vec[UInt8], ck: Str) -> Vec[UInt8] {
  var o = u32be(BITCOIN_MAGIC_MAINNET);
  o = concat(o, ascii(cmd));
  o = concat(o, zeros(12 - string.str_len(cmd)));
  o = concat(o, u32le(payload.len()));
  o = concat(o, hb(ck));
  o = concat(o, payload);
  return o;
}

// Flag-byte-first fragment after a version: used by the rejection tests.
fn fragment(hexstr: Str) -> Vec[UInt8] {
  return hb(hexstr);
}

// --------------------------------------------------
//  t1: CompactSize boundaries
// --------------------------------------------------

fn t1() -> TestResult {
  var ok = true;
  if !bytes_equal(cs_enc(0), hb("00")) { ok = false; }
  if !bytes_equal(cs_enc(252), hb("fc")) { ok = false; }
  if !bytes_equal(cs_enc(253), hb("fdfd00")) { ok = false; }
  if !bytes_equal(cs_enc(65535), hb("fdffff")) { ok = false; }
  if !bytes_equal(cs_enc(65536), hb("fe00000100")) { ok = false; }
  if !bytes_equal(cs_enc(4294967295), hb("feffffffff")) { ok = false; }
  if !bytes_equal(cs_enc(4294967296), hb("ff0000000001000000")) { ok = false; }
  if !bytes_equal(cs_enc(9223372036854775807), hb("ffffffffffffffff7f")) { ok = false; }
  if !cs_ok_is(hb("00"), 0) { ok = false; }
  if !cs_ok_is(hb("fc"), 252) { ok = false; }
  if !cs_ok_is(hb("fdfd00"), 253) { ok = false; }
  if !cs_ok_is(hb("fdffff"), 65535) { ok = false; }
  if !cs_ok_is(hb("fe00000100"), 65536) { ok = false; }
  if !cs_ok_is(hb("feffffffff"), 4294967295) { ok = false; }
  if !cs_ok_is(hb("ff0000000001000000"), 4294967296) { ok = false; }
  if !cs_ok_is(hb("ffffffffffffffff7f"), 9223372036854775807) { ok = false; }
  if compact_size_encoded_len(0) != 1 { ok = false; }
  if compact_size_encoded_len(252) != 1 { ok = false; }
  if compact_size_encoded_len(253) != 3 { ok = false; }
  if compact_size_encoded_len(65536) != 5 { ok = false; }
  if compact_size_encoded_len(4294967296) != 9 { ok = false; }
  // decoding stops exactly after the last varint byte
  var r = reader_new(concat(hb("fdffff"), hb("aa")));
  let d = compact_size_read(&mut r);
  if !d.is_ok { ok = false; }
  if reader_pos(&r) != 3 { ok = false; }
  return assert(ok, "compact size boundary encodings and decodings");
}

// --------------------------------------------------
//  t2: CompactSize truncation, non-canonical forms, overflow
// --------------------------------------------------

fn t2() -> TestResult {
  var ok = true;
  if !streq(int_err(cs_dec(hb("fd"))), "bitcoin: truncated at offset 1") { ok = false; }
  if !streq(int_err(cs_dec(hb("fe0102"))), "bitcoin: truncated at offset 1") { ok = false; }
  if !streq(int_err(cs_dec(hb("ff01020304050607"))), "bitcoin: truncated at offset 1") { ok = false; }
  if !streq(int_err(cs_dec(hb("fdfc00"))), "bitcoin: non-canonical compact size at offset 0") { ok = false; }
  if !streq(int_err(cs_dec(hb("fe2c010000"))), "bitcoin: non-canonical compact size at offset 0") { ok = false; }
  if !streq(int_err(cs_dec(hb("ff2c01000000000000"))), "bitcoin: non-canonical compact size at offset 0") { ok = false; }
  if !streq(int_err(cs_dec(hb("ffffffffffffffffff"))), "bitcoin: unsigned 64-bit value exceeds signed 64-bit range at offset 0") { ok = false; }
  if !streq(int_err(cs_dec(hb("ff0000000000000080"))), "bitcoin: unsigned 64-bit value exceeds signed 64-bit range at offset 0") { ok = false; }
  // the error offset points at the varint's first byte, not the cursor
  var r = reader_new(hb("aafdfc00"));
  let sk = reader_skip(&mut r, 1);
  if !sk.is_ok { ok = false; }
  if !streq(int_err(compact_size_read(&mut r)), "bitcoin: non-canonical compact size at offset 1") { ok = false; }
  return assert(ok, "compact size rejects truncation, non-minimal forms and overflow");
}

// --------------------------------------------------
//  t3: legacy varint, varstr, reader bounds
// --------------------------------------------------

fn t3() -> TestResult {
  var ok = true;
  // legacy varint accepts the non-minimal encoding CompactSize rejects
  let lv = var_dec(hb("fdfc00"));
  if !lv.is_ok { ok = false; } else {
    let n: Int = lv.value;
    if n != 252 { ok = false; }
  }
  let lv2 = var_dec(hb("ff0000000001000000"));
  if !lv2.is_ok { ok = false; } else {
    let n2: Int = lv2.value;
    if n2 != 4294967296 { ok = false; }
  }
  // varstr round trip
  var r = reader_new(hb("03aabbcc"));
  let v = varstr_read(&mut r);
  if !v.is_ok { ok = false; } else {
    let b: Vec[UInt8] = v.value;
    if !bytes_equal(b, hb("aabbcc")) { ok = false; }
  }
  if reader_pos(&r) != 4 { ok = false; }
  var r2 = reader_new(hb("00"));
  let v2 = varstr_read(&mut r2);
  if !v2.is_ok { ok = false; } else {
    let b2: Vec[UInt8] = v2.value;
    if b2.len() != 0 { ok = false; }
  }
  if !streq(bytes_err(varstr_read(&mut r2)), "bitcoin: truncated at offset 1") { ok = false; }
  var r3 = reader_new(hb("05aabb"));
  if !streq(bytes_err(varstr_read(&mut r3)), "bitcoin: truncated at offset 1") { ok = false; }
  var o = Vec[UInt8].new();
  var payload = hb("aabbcc");
  varstr_write(&mut o, &payload);
  if !bytes_equal(o, hb("03aabbcc")) { ok = false; }
  // reader basics and byte-offset errors (mutable and immutable accesses
  // are kept on separate reader values to avoid v0.61.3 E001 advisories)
  var r0 = reader_new(hb("aabb"));
  let l0 = reader_len(&r0);
  let p0 = reader_pos(&r0);
  let m0 = reader_remaining(&r0);
  if l0 != 2 { ok = false; }
  if p0 != 0 { ok = false; }
  if m0 != 2 { ok = false; }
  var r4 = reader_new(hb("aabb"));
  let b0 = reader_byte(&mut r4);
  if !b0.is_ok { ok = false; } else {
    let x: Int = b0.value;
    if x != 170 { ok = false; }
  }
  let b1 = reader_byte(&mut r4);
  if !b1.is_ok { ok = false; } else {
    let y: Int = b1.value;
    if y != 187 { ok = false; }
  }
  if !streq(int_err(reader_byte(&mut r4)), "bitcoin: truncated at offset 2") { ok = false; }
  var r5 = reader_new(hb("aabb"));
  let e5a = bytes_err(reader_take(&mut r5, 3));
  let e5b = bytes_err(reader_take(&mut r5, -1));
  if !streq(e5a, "bitcoin: truncated at offset 0") { ok = false; }
  if !streq(e5b, "bitcoin: negative length at offset 0") { ok = false; }
  var r6 = reader_new(hb("aabb"));
  let s5 = reader_skip(&mut r6, 1);
  if !s5.is_ok { ok = false; }
  let e5c = int_err(reader_skip(&mut r6, 5));
  if !streq(e5c, "bitcoin: truncated at offset 1") { ok = false; }
  var r7 = reader_new(hb("aabb"));
  let sk1 = reader_skip(&mut r7, 1);
  let p7 = reader_pos(&r7);
  let m7 = reader_remaining(&r7);
  if !sk1.is_ok { ok = false; }
  if p7 != 1 { ok = false; }
  if m7 != 1 { ok = false; }
  return assert(ok, "legacy varint, varstr and reader bounds");
}

// --------------------------------------------------
//  t4: message framing
// --------------------------------------------------

fn t4() -> TestResult {
  var ok = true;
  let frame = frame_of("version", version_bytes(), "01020304");
  var r = reader_new(frame);
  let h = message_header_read(&mut r, BITCOIN_MAGIC_MAINNET);
  if !h.is_ok { ok = false; } else {
    let m: MessageHeader = h.value;
    if m.magic != BITCOIN_MAGIC_MAINNET { ok = false; }
    let cmd: Str = m.command;
    if !streq(cmd, "version") { ok = false; }
    let raw: Vec[UInt8] = m.command_raw;
    if raw.len() != 12 { ok = false; }
    if m.payload_len != 98 { ok = false; }
    let ck: Vec[UInt8] = m.checksum;
    if !bytes_equal(ck, hb("01020304")) { ok = false; }
    if m.payload_start != 24 { ok = false; }
    if message_payload_end(&m) != 122 { ok = false; }
    let pl = message_payload_read(&mut r, &m);
    if !pl.is_ok { ok = false; } else {
      let pb: Vec[UInt8] = pl.value;
      if !bytes_equal(pb, version_bytes()) { ok = false; }
    }
    if reader_pos(&r) != 122 { ok = false; }
  }
  // network classification
  if !streq(bitcoin_network_name(BITCOIN_MAGIC_MAINNET), "mainnet") { ok = false; }
  if !streq(bitcoin_network_name(BITCOIN_MAGIC_TESTNET3), "testnet") { ok = false; }
  if !streq(bitcoin_network_name(BITCOIN_MAGIC_REGTEST), "regtest") { ok = false; }
  if !streq(bitcoin_network_name(BITCOIN_MAGIC_SIGNET), "signet") { ok = false; }
  if !streq(bitcoin_network_name(0), "unknown") { ok = false; }
  if !bitcoin_magic_known(BITCOIN_MAGIC_REGTEST) { ok = false; }
  if bitcoin_magic_known(0) { ok = false; }
  // wrong magic
  let tf = frame_of("version", version_bytes(), "01020304");
  var r2 = reader_new(tf);
  if !streq(header_err(message_header_read(&mut r2, BITCOIN_MAGIC_REGTEST)), "bitcoin: wrong network magic at offset 0") { ok = false; }
  // truncated header
  var r3 = reader_new(hb("f9beb4d9"));
  if !streq(header_err(message_header_read(&mut r3, BITCOIN_MAGIC_MAINNET)), "bitcoin: truncated at offset 4") { ok = false; }
  // command padding: a non-NUL byte after the first NUL
  var bp = concat(u32be(BITCOIN_MAGIC_MAINNET), ascii("tx"));
  bp = concat(bp, zeros(1));
  bp = concat(bp, ascii("X"));
  bp = concat(bp, zeros(8));
  bp = concat(bp, u32le(0));
  bp = concat(bp, hb("00000000"));
  var r4 = reader_new(bp);
  if !streq(header_err(message_header_read(&mut r4, BITCOIN_MAGIC_MAINNET)), "bitcoin: bad command padding at offset 7") { ok = false; }
  // command character below the printable range
  var bc = concat(u32be(BITCOIN_MAGIC_MAINNET), ascii("t"));
  bc = concat(bc, rep_byte(1, 1));
  bc = concat(bc, zeros(10));
  bc = concat(bc, u32le(0));
  bc = concat(bc, hb("00000000"));
  var r5 = reader_new(bc);
  if !streq(header_err(message_header_read(&mut r5, BITCOIN_MAGIC_MAINNET)), "bitcoin: bad command character at offset 5") { ok = false; }
  // all-NUL command is accepted with an empty name
  var ec = concat(u32be(BITCOIN_MAGIC_MAINNET), zeros(12));
  ec = concat(ec, u32le(0));
  ec = concat(ec, hb("00000000"));
  var r6 = reader_new(ec);
  let eh = message_header_read(&mut r6, BITCOIN_MAGIC_MAINNET);
  if !eh.is_ok { ok = false; } else {
    let em: MessageHeader = eh.value;
    let ecs: Str = em.command;
    if !streq(ecs, "") { ok = false; }
  }
  // payload length above the documented cap
  var oc = concat(u32be(BITCOIN_MAGIC_MAINNET), ascii("tx"));
  oc = concat(oc, zeros(10));
  oc = concat(oc, u32le(33554433));
  oc = concat(oc, hb("00000000"));
  var r7 = reader_new(oc);
  if !streq(header_err(message_header_read(&mut r7, BITCOIN_MAGIC_MAINNET)), "bitcoin: payload length 33554433 exceeds cap 33554432 at offset 16") { ok = false; }
  return assert(ok, "message framing magic, command, cap and checksum");
}

// --------------------------------------------------
//  t5: version message and u64 helpers
// --------------------------------------------------

fn t5() -> TestResult {
  var ok = true;
  var r = reader_new(version_bytes());
  let v = version_message_read(&mut r);
  if !v.is_ok { ok = false; } else {
    let m: VersionMessage = v.value;
    if m.version != 70015 { ok = false; }
    let svc: Vec[UInt8] = m.services;
    if !bytes_equal(svc, hb("0900000000000000")) { ok = false; }
    if bitcoin_u64_to_int(&svc) != 9 { ok = false; }
    if !bitcoin_u64_fits_int(&svc) { ok = false; }
    if m.timestamp != 1231006505 { ok = false; }
    let recv: NetAddress = m.addr_recv;
    if recv.port != 8333 { ok = false; }
    let rip: Vec[UInt8] = recv.ip;
    if rip.len() != 16 { ok = false; }
    if net_address_ipv4(&rip).len() != 0 { ok = false; }
    let from: NetAddress = m.addr_from;
    if from.port != 8334 { ok = false; }
    let fip: Vec[UInt8] = from.ip;
    if !bytes_equal(net_address_ipv4(&fip), hb("0a000001")) { ok = false; }
    let fsvc: Vec[UInt8] = from.services;
    if bitcoin_u64_to_int(&fsvc) != 1 { ok = false; }
    let nonce: Vec[UInt8] = m.nonce;
    if !bytes_equal(nonce, hb("0807060504030201")) { ok = false; }
    let ua: Vec[UInt8] = m.user_agent;
    if !bytes_equal(ua, ascii("/xiom:0.1.0/")) { ok = false; }
    if m.start_height != 800000 { ok = false; }
    if m.relay != 1 { ok = false; }
    if reader_remaining(&r) != 0 { ok = false; }
  }
  // relay absent: the optional byte is not there
  var r2 = reader_new(version_no_relay_bytes());
  let v2 = version_message_read(&mut r2);
  if !v2.is_ok { ok = false; } else {
    let m2: VersionMessage = v2.value;
    if m2.relay != -1 { ok = false; }
    if reader_remaining(&r2) != 0 { ok = false; }
  }
  // u64 raw-byte helpers
  if !bytes_equal(bitcoin_u64_le_bytes(9), hb("0900000000000000")) { ok = false; }
  if bitcoin_u64_fits_int(&hb("0000000000000080")) { ok = false; }
  if bitcoin_u64_to_int(&hb("0000000000000080")) != -1 { ok = false; }
  if bitcoin_u64_le_bytes(-1).len() != 0 { ok = false; }
  return assert(ok, "version message fields and u64 byte helpers");
}

// --------------------------------------------------
//  t6: verack and a full framed transaction walk
// --------------------------------------------------

fn t6() -> TestResult {
  var ok = true;
  // verack: zero-length payload
  let vf = frame_of("verack", Vec[UInt8].new(), "5df6e0e2");
  var r = reader_new(vf);
  let h = message_header_read(&mut r, BITCOIN_MAGIC_MAINNET);
  if !h.is_ok { ok = false; } else {
    let m: MessageHeader = h.value;
    let cmd: Str = m.command;
    if !streq(cmd, "verack") { ok = false; }
    if m.payload_len != 0 { ok = false; }
    let ck: Vec[UInt8] = m.checksum;
    if !bytes_equal(ck, hb("5df6e0e2")) { ok = false; }
    let pl = message_payload_read(&mut r, &m);
    if !pl.is_ok { ok = false; } else {
      let pb: Vec[UInt8] = pl.value;
      if pb.len() != 0 { ok = false; }
    }
    if reader_pos(&r) != 24 { ok = false; }
  }
  // framed legacy tx: header + payload walk
  let tf = frame_of("tx", legacy_tx_bytes(), "deadbeef");
  var r2 = reader_new(tf);
  let h2 = message_header_read(&mut r2, BITCOIN_MAGIC_MAINNET);
  if !h2.is_ok { ok = false; } else {
    let m2: MessageHeader = h2.value;
    let cmd2: Str = m2.command;
    if !streq(cmd2, "tx") { ok = false; }
    if m2.payload_len != 125 { ok = false; }
    if m2.payload_start != 24 { ok = false; }
    if message_payload_end(&m2) != 149 { ok = false; }
    let pl2 = message_payload_read(&mut r2, &m2);
    if !pl2.is_ok { ok = false; } else {
      let pb2: Vec[UInt8] = pl2.value;
      if !bytes_equal(pb2, legacy_tx_bytes()) { ok = false; }
    }
  }
  if reader_pos(&r2) != 149 { ok = false; }
  return assert(ok, "verack and framed transaction walk");
}

// --------------------------------------------------
//  t7: addr message
// --------------------------------------------------

fn t7() -> TestResult {
  var ok = true;
  var r = reader_new(addr_bytes());
  let a = addr_message_read(&mut r);
  if !a.is_ok { ok = false; } else {
    let l: AddressList = a.value;
    if l.count != 2 { ok = false; }
    let t0: Int = l.times[0];
    let t1: Int = l.times[1];
    if t0 != 1231006505 { ok = false; }
    if t1 != 0 { ok = false; }
    let s0: Vec[UInt8] = l.services[0];
    if !bytes_equal(s0, hb("0100000000000000")) { ok = false; }
    if bitcoin_u64_to_int(&s0) != 1 { ok = false; }
    let i0: Vec[UInt8] = l.ips[0];
    if !bytes_equal(net_address_ipv4(&i0), hb("7f000001")) { ok = false; }
    let i1: Vec[UInt8] = l.ips[1];
    if net_address_ipv4(&i1).len() != 0 { ok = false; }
    let p0: Int = l.ports[0];
    let p1: Int = l.ports[1];
    if p0 != 8333 { ok = false; }
    if p1 != 18333 { ok = false; }
    if reader_remaining(&r) != 0 { ok = false; }
  }
  // count cap
  var r2 = reader_new(hb("fde903"));
  if !streq(addrs_err(addr_message_read(&mut r2)), "bitcoin: count 1001 exceeds cap 1000 at offset 3") { ok = false; }
  // truncation after the count
  var r3 = reader_new(hb("02"));
  if !streq(addrs_err(addr_message_read(&mut r3)), "bitcoin: truncated at offset 1") { ok = false; }
  return assert(ok, "addr message entries and count cap");
}

// --------------------------------------------------
//  t8: inv and getdata
// --------------------------------------------------

fn t8() -> TestResult {
  var ok = true;
  var r = reader_new(inv_bytes());
  let iv = inv_message_read(&mut r);
  if !iv.is_ok { ok = false; } else {
    let l: InvList = iv.value;
    if l.count != 2 { ok = false; }
    let t0: Int = l.types[0];
    let t1: Int = l.types[1];
    if t0 != INV_TYPE_TX { ok = false; }
    if t1 != INV_TYPE_BLOCK { ok = false; }
    let h0: Vec[UInt8] = l.hashes[0];
    let h1: Vec[UInt8] = l.hashes[1];
    if !bytes_equal(h0, rep_byte(171, 32)) { ok = false; }
    if !bytes_equal(h1, rep_byte(205, 32)) { ok = false; }
    if reader_remaining(&r) != 0 { ok = false; }
  }
  if !streq(inv_type_name(INV_TYPE_TX), "tx") { ok = false; }
  if !streq(inv_type_name(INV_TYPE_BLOCK), "block") { ok = false; }
  if !streq(inv_type_name(INV_TYPE_FILTERED_BLOCK), "filtered_block") { ok = false; }
  if !streq(inv_type_name(INV_TYPE_CMPCT_BLOCK), "cmpct_block") { ok = false; }
  if !streq(inv_type_name(7), "unknown") { ok = false; }
  if !inv_type_known(INV_TYPE_CMPCT_BLOCK) { ok = false; }
  if inv_type_known(7) { ok = false; }
  // getdata has the same layout
  var r2 = reader_new(inv_bytes());
  let gd = getdata_message_read(&mut r2);
  if !gd.is_ok { ok = false; } else {
    let l2: InvList = gd.value;
    if l2.count != 2 { ok = false; }
  }
  // count cap: 50001 as CompactSize (fd 51 c3)
  var r3 = reader_new(hb("fd51c3"));
  if !streq(inv_err(inv_message_read(&mut r3)), "bitcoin: count 50001 exceeds cap 50000 at offset 3") { ok = false; }
  // empty inventory list
  var r4 = reader_new(hb("00"));
  let e = inv_message_read(&mut r4);
  if !e.is_ok { ok = false; } else {
    let l4: InvList = e.value;
    if l4.count != 0 { ok = false; }
  }
  return assert(ok, "inv/getdata vectors, type names and count cap");
}

// --------------------------------------------------
//  t9: legacy transaction
// --------------------------------------------------

fn t9() -> TestResult {
  var ok = true;
  var r = reader_new(legacy_tx_bytes());
  let tr = tx_read(&mut r);
  if !tr.is_ok { ok = false; } else {
    let t: Tx = tr.value;
    if t.version != 2 { ok = false; }
    if t.segwit { ok = false; }
    if t.in_count != 1 { ok = false; }
    let ph: Vec[UInt8] = t.in_prev_hash[0];
    if !bytes_equal(ph, hb("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")) { ok = false; }
    let pi: Int = t.in_prev_index[0];
    if pi != 0 { ok = false; }
    var want_script = hb("76a914");
    want_script = concat(want_script, rep_byte(17, 20));
    want_script = concat(want_script, hb("88ac"));
    let sc: Vec[UInt8] = t.in_script[0];
    if !bytes_equal(sc, want_script) { ok = false; }
    let sq: Int = t.in_sequence[0];
    if sq != 4294967294 { ok = false; }
    if t.out_count != 2 { ok = false; }
    let v0: Int = t.out_value[0];
    let v1: Int = t.out_value[1];
    if v0 != 5000000000 { ok = false; }
    if v1 != 1000 { ok = false; }
    let os0: Vec[UInt8] = t.out_script[0];
    if !bytes_equal(os0, want_script) { ok = false; }
    let os1: Vec[UInt8] = t.out_script[1];
    if !bytes_equal(os1, hb("6a04deadbeef")) { ok = false; }
    if t.locktime != 15 { ok = false; }
    if t.byte_len != 125 { ok = false; }
    if t.witness_counts.len() != 0 { ok = false; }
    if t.witness_items.len() != 0 { ok = false; }
    if reader_remaining(&r) != 0 { ok = false; }
    // writer round-trip
    var o = Vec[UInt8].new();
    let written = tx_write(&mut o, &t);
    if written != 125 { ok = false; }
    if !bytes_equal(o, legacy_tx_bytes()) { ok = false; }
  }
  return assert(ok, "legacy transaction fields and write round-trip");
}

// --------------------------------------------------
//  t10: SegWit transaction
// --------------------------------------------------

fn t10() -> TestResult {
  var ok = true;
  var r = reader_new(segwit_tx_bytes());
  let tr = tx_read(&mut r);
  if !tr.is_ok { ok = false; } else {
    let t: Tx = tr.value;
    if t.version != 2 { ok = false; }
    if !t.segwit { ok = false; }
    if t.in_count != 1 { ok = false; }
    if t.out_count != 2 { ok = false; }
    let ph: Vec[UInt8] = t.in_prev_hash[0];
    if !bytes_equal(ph, rep_byte(255, 32)) { ok = false; }
    let pi: Int = t.in_prev_index[0];
    if pi != 4294967295 { ok = false; }
    let sc: Vec[UInt8] = t.in_script[0];
    if sc.len() != 0 { ok = false; }
    let sq: Int = t.in_sequence[0];
    if sq != 4294967295 { ok = false; }
    let v0: Int = t.out_value[0];
    let v1: Int = t.out_value[1];
    if v0 != 100000 { ok = false; }
    if v1 != 0 { ok = false; }
    var want_spk = hb("0014");
    want_spk = concat(want_spk, rep_byte(34, 20));
    let os0: Vec[UInt8] = t.out_script[0];
    if !bytes_equal(os0, want_spk) { ok = false; }
    let os1: Vec[UInt8] = t.out_script[1];
    if !bytes_equal(os1, hb("6a")) { ok = false; }
    if t.witness_counts.len() != 1 { ok = false; }
    let wc: Int = t.witness_counts[0];
    if wc != 2 { ok = false; }
    let ws: Int = t.witness_flat_start[0];
    if ws != 0 { ok = false; }
    if t.witness_items.len() != 2 { ok = false; }
    let w0: Vec[UInt8] = t.witness_items[0];
    if !bytes_equal(w0, hb("aabbcc")) { ok = false; }
    var want_w1 = hb("03");
    want_w1 = concat(want_w1, rep_byte(68, 32));
    let w1: Vec[UInt8] = t.witness_items[1];
    if !bytes_equal(w1, want_w1) { ok = false; }
    if t.locktime != 0 { ok = false; }
    if t.byte_len != 133 { ok = false; }
    if reader_remaining(&r) != 0 { ok = false; }
    // writer round-trip
    var o = Vec[UInt8].new();
    let written = tx_write(&mut o, &t);
    if written != 133 { ok = false; }
    if !bytes_equal(o, segwit_tx_bytes()) { ok = false; }
  }
  return assert(ok, "segwit transaction marker, witness stack and write round-trip");
}

// --------------------------------------------------
//  t11: transaction rejections
// --------------------------------------------------

fn t11() -> TestResult {
  var ok = true;
  // zero inputs without a witness flag: version + 00 + 00
  var r = reader_new(hb("020000000000"));
  if !streq(tx_err(tx_read(&mut r)), "bitcoin: zero-input transaction without witness flag at offset 5") { ok = false; }
  // unsupported flag value 2
  var r2 = reader_new(hb("020000000002"));
  if !streq(tx_err(tx_read(&mut r2)), "bitcoin: unsupported witness flag 2 at offset 5") { ok = false; }
  // marker + flag but zero real inputs
  var r3 = reader_new(hb("02000000000100"));
  if !streq(tx_err(tx_read(&mut r3)), "bitcoin: zero-input witness transaction at offset 0") { ok = false; }
  // input count above the cap (1000001)
  var r4 = reader_new(hb("02000000fe41420f00"));
  if !streq(tx_err(tx_read(&mut r4)), "bitcoin: count 1000001 exceeds cap 1000000 at offset 9") { ok = false; }
  // truncated prev hash
  var r5 = reader_new(hb("02000000010011"));
  if !streq(tx_err(tx_read(&mut r5)), "bitcoin: truncated at offset 5") { ok = false; }
  // output count above the cap, after a complete input
  var r6 = reader_new(fragment("020000000100000000000000000000000000000000000000000000000000000000000000000000000000fffffffffe41420f00"));
  if !streq(tx_err(tx_read(&mut r6)), "bitcoin: count 1000001 exceeds cap 1000000 at offset 51") { ok = false; }
  return assert(ok, "transaction rejects bad flags, empty inputs and oversized counts");
}

// --------------------------------------------------
//  t12: block header and block walk
// --------------------------------------------------

fn t12() -> TestResult {
  var ok = true;
  var r = reader_new(gen_header_bytes());
  let hr = block_header_read(&mut r);
  if !hr.is_ok { ok = false; } else {
    let h: BlockHeader = hr.value;
    if h.version != 1 { ok = false; }
    let ph: Vec[UInt8] = h.prev_hash;
    if !bytes_equal(ph, zeros(32)) { ok = false; }
    let mr: Vec[UInt8] = h.merkle_root;
    if !bytes_equal(mr, hb("3ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4a")) { ok = false; }
    if h.time != 1231006505 { ok = false; }
    if h.bits != 486604799 { ok = false; }
    if h.nonce != 2083236893 { ok = false; }
    if reader_remaining(&r) != 0 { ok = false; }
    var o = Vec[UInt8].new();
    let w = block_header_write(&mut o, &h);
    if w != 80 { ok = false; }
    if !bytes_equal(o, gen_header_bytes()) { ok = false; }
  }
  // the genesis block: header + tx count 1 + the coinbase
  var r2 = reader_new(gen_block_bytes());
  let br = block_read(&mut r2);
  if !br.is_ok { ok = false; } else {
    let b: Block = br.value;
    if b.tx_count != 1 { ok = false; }
    if b.tx_bytes_start != 81 { ok = false; }
    if b.tx_bytes_end != 285 { ok = false; }
    if b.byte_len != 285 { ok = false; }
    let bh: BlockHeader = b.header;
    if bh.version != 1 { ok = false; }
    if bh.nonce != 2083236893 { ok = false; }
    if reader_remaining(&r2) != 0 { ok = false; }
  }
  // re-read the consumed tx stream from the recorded start offset
  var r3 = reader_new(gen_block_bytes());
  let sk = reader_skip(&mut r3, 81);
  if !sk.is_ok { ok = false; }
  let tr = tx_read(&mut r3);
  if !tr.is_ok { ok = false; } else {
    let t: Tx = tr.value;
    if t.version != 1 { ok = false; }
    if t.in_count != 1 { ok = false; }
    if t.out_count != 1 { ok = false; }
    let idx: Int = t.in_prev_index[0];
    if idx != 4294967295 { ok = false; }
    let ph2: Vec[UInt8] = t.in_prev_hash[0];
    if !bytes_equal(ph2, zeros(32)) { ok = false; }
    let seq: Int = t.in_sequence[0];
    if seq != 4294967295 { ok = false; }
    let val: Int = t.out_value[0];
    if val != 5000000000 { ok = false; }
    if t.locktime != 0 { ok = false; }
    if t.byte_len != 204 { ok = false; }
    // the coinbase input script: push4(f0ffff001d style), push1, push69
    let isc: Vec[UInt8] = t.in_script[0];
    let sr = script_parse(&isc);
    if !sr.is_ok { ok = false; } else {
      let d: ScriptDoc = sr.value;
      if d.op_count != 3 { ok = false; }
      let p0: Int = d.push_len[0];
      let p1: Int = d.push_len[1];
      let p2: Int = d.push_len[2];
      if p0 != 4 { ok = false; }
      if p1 != 1 { ok = false; }
      if p2 != 69 { ok = false; }
      let head = script_data(&d, 2);
      if !bytes_equal(head, ascii("The Times 03/Jan/2009 Chancellor on brink of second bailout for banks")) { ok = false; }
    }
    // the output script: push65(pubkey) + OP_CHECKSIG
    let osc: Vec[UInt8] = t.out_script[0];
    let sr2 = script_parse(&osc);
    if !sr2.is_ok { ok = false; } else {
      let d2: ScriptDoc = sr2.value;
      if d2.op_count != 2 { ok = false; }
      if script_opcode(&d2, 0) != 65 { ok = false; }
      if script_opcode(&d2, 1) != OP_CHECKSIG { ok = false; }
    }
  }
  // block tx count cap
  var cap = gen_header_bytes();
  cap = concat(cap, hb("fe41420f00"));
  var r4 = reader_new(cap);
  if !streq(block_err(block_read(&mut r4)), "bitcoin: count 1000001 exceeds cap 1000000 at offset 85") { ok = false; }
  return assert(ok, "genesis block header, coinbase walk and tx count cap");
}

// --------------------------------------------------
//  t13: script push parsing
// --------------------------------------------------

fn t13() -> TestResult {
  var ok = true;
  var script = hb("00");
  script = concat(script, hb("51"));
  script = concat(script, hb("4c02aabb"));
  script = concat(script, hb("4d0300ccddee"));
  script = concat(script, hb("4e04000000deadbeef"));
  script = concat(script, hb("76a988ac"));
  let sr = script_parse(&script);
  if !sr.is_ok { ok = false; } else {
    let d: ScriptDoc = sr.value;
    if d.script_len != 25 { ok = false; }
    if d.op_count != 9 { ok = false; }
    if script_opcode(&d, 0) != OP_0 { ok = false; }
    if script_opcode(&d, 1) != OP_1 { ok = false; }
    if script_opcode(&d, 2) != OP_PUSHDATA1 { ok = false; }
    if script_opcode(&d, 3) != OP_PUSHDATA2 { ok = false; }
    if script_opcode(&d, 4) != OP_PUSHDATA4 { ok = false; }
    if script_opcode(&d, 5) != OP_DUP { ok = false; }
    if script_opcode(&d, 6) != OP_HASH160 { ok = false; }
    if script_opcode(&d, 7) != OP_EQUALVERIFY { ok = false; }
    if script_opcode(&d, 8) != OP_CHECKSIG { ok = false; }
    if script_push_len(&d, 0) != 0 { ok = false; }
    if script_push_len(&d, 1) != 1 { ok = false; }
    if script_push_len(&d, 2) != 2 { ok = false; }
    if script_push_len(&d, 3) != 3 { ok = false; }
    if script_push_len(&d, 4) != 4 { ok = false; }
    if script_push_len(&d, 5) != -1 { ok = false; }
    if script_push_len(&d, 99) != -1 { ok = false; }
    if !bytes_equal(script_data(&d, 0), Vec[UInt8].new()) { ok = false; }
    if !bytes_equal(script_data(&d, 2), hb("aabb")) { ok = false; }
    if !bytes_equal(script_data(&d, 3), hb("ccddee")) { ok = false; }
    if !bytes_equal(script_data(&d, 4), hb("deadbeef")) { ok = false; }
    if !streq(script_op_name(script_opcode(&d, 0)), "OP_0") { ok = false; }
    if !streq(script_op_name(script_opcode(&d, 1)), "OP_1") { ok = false; }
    if !streq(script_op_name(script_opcode(&d, 2)), "OP_PUSHDATA1") { ok = false; }
    if !streq(script_op_name(script_opcode(&d, 3)), "OP_PUSHDATA2") { ok = false; }
    if !streq(script_op_name(script_opcode(&d, 4)), "OP_PUSHDATA4") { ok = false; }
    if !streq(script_op_name(script_opcode(&d, 5)), "OP_DUP") { ok = false; }
    if !streq(script_op_name(script_opcode(&d, 6)), "OP_HASH160") { ok = false; }
    if !streq(script_op_name(script_opcode(&d, 7)), "OP_EQUALVERIFY") { ok = false; }
    if !streq(script_op_name(script_opcode(&d, 8)), "OP_CHECKSIG") { ok = false; }
    if script_is_push_only(&d) { ok = false; }
  }
  // push-only scripts
  let po = hb("0051");
  let pr = script_parse(&po);
  if !pr.is_ok { ok = false; } else {
    let pd: ScriptDoc = pr.value;
    if !script_is_push_only(&pd) { ok = false; }
  }
  if !streq(script_op_name(OP_16), "OP_16") { ok = false; }
  if !streq(script_op_name(OP_1NEGATE), "OP_1NEGATE") { ok = false; }
  if !streq(script_op_name(OP_CHECKLOCKTIMEVERIFY), "OP_CHECKLOCKTIMEVERIFY") { ok = false; }
  if !streq(script_op_name(OP_CHECKSEQUENCEVERIFY), "OP_CHECKSEQUENCEVERIFY") { ok = false; }
  if !streq(script_op_name(OP_RETURN), "OP_RETURN") { ok = false; }
  if !streq(script_op_name(OP_CHECKMULTISIG), "OP_CHECKMULTISIG") { ok = false; }
  if !streq(script_op_name(OP_EQUAL), "OP_EQUAL") { ok = false; }
  if !streq(script_op_name(0xBA), "OP_UNKNOWN") { ok = false; }
  // bounds errors
  let b1 = hb("4c05aabb");
  if !streq(script_err(script_parse(&b1)), "bitcoin: script push exceeds script at offset 0") { ok = false; }
  let b2 = hb("4c");
  if !streq(script_err(script_parse(&b2)), "bitcoin: truncated pushdata at offset 0") { ok = false; }
  let b3 = hb("4d01");
  if !streq(script_err(script_parse(&b3)), "bitcoin: truncated pushdata at offset 0") { ok = false; }
  let b4 = hb("4e010000");
  if !streq(script_err(script_parse(&b4)), "bitcoin: truncated pushdata at offset 0") { ok = false; }
  let b5 = hb("03aabb");
  if !streq(script_err(script_parse(&b5)), "bitcoin: script push exceeds script at offset 0") { ok = false; }
  return assert(ok, "script push parsing, opcode names and bounds");
}

// --------------------------------------------------
//  t14: script template classification
// --------------------------------------------------

fn t14() -> TestResult {
  var ok = true;
  var pkh = concat(hb("76a914"), rep_byte(17, 20));
  pkh = concat(pkh, hb("88ac"));
  var sh = concat(hb("a914"), rep_byte(34, 20));
  sh = concat(sh, hb("87"));
  var wpkh = concat(hb("0014"), rep_byte(51, 20));
  var wsh = concat(hb("0020"), rep_byte(68, 32));
  var tr = concat(hb("5120"), rep_byte(85, 32));
  var opret = hb("6a04deadbeef");
  let unk76 = hb("76");
  if !streq(script_classify(&pkh), "p2pkh") { ok = false; }
  if !streq(script_classify(&sh), "p2sh") { ok = false; }
  if !streq(script_classify(&wpkh), "p2wpkh") { ok = false; }
  if !streq(script_classify(&wsh), "p2wsh") { ok = false; }
  if !streq(script_classify(&tr), "p2tr") { ok = false; }
  if !streq(script_classify(&opret), "op_return") { ok = false; }
  if !streq(script_classify(&unk76), "unknown") { ok = false; }
  let unk_empty = Vec[UInt8].new();
  if !streq(script_classify(&unk_empty), "unknown") { ok = false; }
  if !bytes_equal(script_template_payload(&pkh), rep_byte(17, 20)) { ok = false; }
  if !bytes_equal(script_template_payload(&sh), rep_byte(34, 20)) { ok = false; }
  if !bytes_equal(script_template_payload(&wpkh), rep_byte(51, 20)) { ok = false; }
  if !bytes_equal(script_template_payload(&wsh), rep_byte(68, 32)) { ok = false; }
  if !bytes_equal(script_template_payload(&tr), rep_byte(85, 32)) { ok = false; }
  if script_template_payload(&opret).len() != 0 { ok = false; }
  // p2tr with the wrong program length is unknown
  var badtr = concat(hb("5120"), rep_byte(85, 20));
  if !streq(script_classify(&badtr), "unknown") { ok = false; }
  return assert(ok, "script template classification and payload extraction");
}

// --------------------------------------------------
//  t15: Base58
// --------------------------------------------------

fn t15() -> TestResult {
  var ok = true;
  if !streq(base58_encode(&ascii("Hello World")), "JxF12TrwUP45BMd") { ok = false; }
  let hw = base58_decode("JxF12TrwUP45BMd");
  if !hw.is_ok { ok = false; } else {
    let b: Vec[UInt8] = hw.value;
    if !bytes_equal(b, ascii("Hello World")) { ok = false; }
  }
  // genesis address round-trip: decode, split payload/checksum, re-encode
  let gd = base58_decode("1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa");
  if !gd.is_ok { ok = false; } else {
    let raw: Vec[UInt8] = gd.value;
    if !bytes_equal(raw, hb("0062e907b15cbf27d5425399ebf6f0fb50ebb88f18c29b7d93")) { ok = false; }
    if !bytes_equal(base58_payload(&raw), hb("0062e907b15cbf27d5425399ebf6f0fb50ebb88f18")) { ok = false; }
    if !bytes_equal(base58_checksum(&raw), hb("c29b7d93")) { ok = false; }
    if !streq(base58_encode(&raw), "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa") { ok = false; }
  }
  // leading zeros map to leading '1' characters
  if !streq(base58_encode(&hb("000001")), "112") { ok = false; }
  let lz = base58_decode("112");
  if !lz.is_ok { ok = false; } else {
    let b2: Vec[UInt8] = lz.value;
    if !bytes_equal(b2, hb("000001")) { ok = false; }
  }
  let lz3 = base58_decode("111");
  if !lz3.is_ok { ok = false; } else {
    let b3: Vec[UInt8] = lz3.value;
    if !bytes_equal(b3, hb("000000")) { ok = false; }
  }
  // empty input
  let empty_bytes = Vec[UInt8].new();
  if !streq(base58_encode(&empty_bytes), "") { ok = false; }
  let em = base58_decode("");
  if !em.is_ok { ok = false; } else {
    let b4: Vec[UInt8] = em.value;
    if b4.len() != 0 { ok = false; }
  }
  // short blobs have no payload/checksum split
  if base58_payload(&hb("aabb")).len() != 0 { ok = false; }
  if base58_checksum(&hb("aabb")).len() != 0 { ok = false; }
  // invalid alphabet
  if !streq(bytes_err(base58_decode("0")), "bitcoin: base58 invalid character at offset 0") { ok = false; }
  if !streq(bytes_err(base58_decode("O")), "bitcoin: base58 invalid character at offset 0") { ok = false; }
  if !streq(bytes_err(base58_decode("abc0")), "bitcoin: base58 invalid character at offset 3") { ok = false; }
  if base58_is_valid("abc0") { ok = false; }
  if !base58_is_valid("JxF12TrwUP45BMd") { ok = false; }
  // input length cap
  let long = string.str_repeat("1", 1025);
  if !streq(bytes_err(base58_decode(long)), "bitcoin: base58 input too long") { ok = false; }
  return assert(ok, "base58 alphabet, leading zeros and mainnet address round-trip");
}

// --------------------------------------------------
//  t16: Bech32/Bech32m valid vectors and encoding
// --------------------------------------------------

fn t16() -> TestResult {
  var ok = true;
  let a = bech32_decode("A12UEL5L");
  if !a.is_ok { ok = false; } else {
    let d: Bech32Data = a.value;
    let h: Str = d.hrp;
    if !streq(h, "a") { ok = false; }
    if bech32_variant(&d) != BECH32_VARIANT_BECH32 { ok = false; }
    if bech32_values(&d).len() != 0 { ok = false; }
  }
  let b = bech32_decode("a12uel5l");
  if !b.is_ok { ok = false; }
  let s = bech32_decode("split1checkupstagehandshakeupstreamerranterredcaperred2y9e3w");
  if !s.is_ok { ok = false; } else {
    let d2: Bech32Data = s.value;
    let h2: Str = d2.hrp;
    if !streq(h2, "split") { ok = false; }
    if bech32_variant(&d2) != BECH32_VARIANT_BECH32 { ok = false; }
    if bech32_values(&d2).len() != 48 { ok = false; }
  }
  let q = bech32_decode("?1ezyfcl");
  if !q.is_ok { ok = false; } else {
    let d3: Bech32Data = q.value;
    let h3: Str = d3.hrp;
    if !streq(h3, "?") { ok = false; }
  }
  // Bech32m vectors
  let m1 = bech32_decode("A1LQFN3A");
  if !m1.is_ok { ok = false; } else {
    let d4: Bech32Data = m1.value;
    if bech32_variant(&d4) != BECH32_VARIANT_BECH32M { ok = false; }
  }
  let m2 = bech32_decode("abcdef1l7aum6echk45nj3s0wdvt2fg8x9yrzpqzd3ryx");
  if !m2.is_ok { ok = false; } else {
    let d5: Bech32Data = m2.value;
    let h5: Str = d5.hrp;
    if !streq(h5, "abcdef") { ok = false; }
    if bech32_variant(&d5) != BECH32_VARIANT_BECH32M { ok = false; }
    let vals = bech32_values(&d5);
    if vals.len() != 32 { ok = false; }
    let first: Int = vals[0];
    let last: Int = vals[31];
    if first != 31 { ok = false; }
    if last != 0 { ok = false; }
  }
  let m3 = bech32_decode("11llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllludsr8");
  if !m3.is_ok { ok = false; } else {
    let d6: Bech32Data = m3.value;
    let h6: Str = d6.hrp;
    if !streq(h6, "1") { ok = false; }
    if bech32_variant(&d6) != BECH32_VARIANT_BECH32M { ok = false; }
    if bech32_values(&d6).len() != 82 { ok = false; }
  }
  let m4 = bech32_decode("split1checkupstagehandshakeupstreamerranterredcaperredlc445v");
  if !m4.is_ok { ok = false; } else {
    let d7: Bech32Data = m4.value;
    if bech32_variant(&d7) != BECH32_VARIANT_BECH32M { ok = false; }
    if bech32_values(&d7).len() != 48 { ok = false; }
  }
  let m5 = bech32_decode("?1v759aa");
  if !m5.is_ok { ok = false; } else {
    let d8: Bech32Data = m5.value;
    if bech32_variant(&d8) != BECH32_VARIANT_BECH32M { ok = false; }
  }
  // canonical lowercase emission
  var empty = Vec[Int].new();
  let e1 = bech32_encode("?", &empty, BECH32_VARIANT_BECH32);
  if !e1.is_ok { ok = false; } else {
    let s1: Str = e1.value;
    if !streq(s1, "?1ezyfcl") { ok = false; }
  }
  let e2 = bech32_encode("?", &empty, BECH32_VARIANT_BECH32M);
  if !e2.is_ok { ok = false; } else {
    let s2: Str = e2.value;
    if !streq(s2, "?1v759aa") { ok = false; }
  }
  var desc = Vec[Int].new();
  var i = 31;
  while i >= 0 {
    desc.push(i);
    i = i - 1;
  }
  let e3 = bech32_encode("abcdef", &desc, BECH32_VARIANT_BECH32M);
  if !e3.is_ok { ok = false; } else {
    let s3: Str = e3.value;
    if !streq(s3, "abcdef1l7aum6echk45nj3s0wdvt2fg8x9yrzpqzd3ryx") { ok = false; }
  }
  // 8->5 and 5->8 conversion round-trip
  let prog = hb("751e76e8199196d454941c45d1b3a323f1433bd6");
  let sym = bech32_bytes_to_symbols(&prog);
  if sym.len() != 32 { ok = false; }
  let back = bech32_symbols_to_bytes(&sym);
  if !back.is_ok { ok = false; } else {
    let bb: Vec[UInt8] = back.value;
    if !bytes_equal(bb, prog) { ok = false; }
  }
  return assert(ok, "bech32/bech32m valid vectors, encoding and convertbits");
}

// --------------------------------------------------
//  t17: Bech32/Bech32m rejections
// --------------------------------------------------

fn t17() -> TestResult {
  var ok = true;
  if !streq(bech32_err(bech32_decode("A12UEL5X")), "bitcoin: bech32 bad checksum") { ok = false; }
  if !streq(bech32_err(bech32_decode("A12uEL5L")), "bitcoin: bech32 mixed case") { ok = false; }
  if !streq(bech32_err(bech32_decode("A1")), "bitcoin: bech32 bad length") { ok = false; }
  if !streq(bech32_err(bech32_decode("1ezyfclz")), "bitcoin: bech32 missing separator") { ok = false; }
  if !streq(bech32_err(bech32_decode("?1ezyfcb")), "bitcoin: bech32 invalid data character") { ok = false; }
  if !streq(bech32_err(bech32_decode("? 1ezyfcl")), "bitcoin: bech32 invalid hrp character") { ok = false; }
  let lng = string.str_repeat("a", 91);
  if !streq(bech32_err(bech32_decode(lng)), "bitcoin: bech32 bad length") { ok = false; }
  // encode errors
  var empty = Vec[Int].new();
  if !streq(str_err(bech32_encode("bc", &empty, 5)), "bitcoin: bech32 bad variant") { ok = false; }
  if !streq(str_err(bech32_encode("", &empty, 0)), "bitcoin: bech32 invalid hrp length") { ok = false; }
  if !streq(str_err(bech32_encode("BC", &empty, 0)), "bitcoin: bech32 mixed case") { ok = false; }
  var bad = Vec[Int].new();
  bad.push(32);
  if !streq(str_err(bech32_encode("bc", &bad, 0)), "bitcoin: bech32 invalid data value") { ok = false; }
  // a result that would exceed 90 characters
  let hrp83 = string.str_repeat("a", 83);
  var longdata = Vec[Int].new();
  var i = 0;
  while i < 5 {
    longdata.push(1);
    i = i + 1;
  }
  if !streq(str_err(bech32_encode(hrp83, &longdata, 0)), "bitcoin: bech32 bad length") { ok = false; }
  // convertbits errors
  var one = Vec[Int].new();
  one.push(0);
  if !streq(ints_err(bech32_convertbits(&one, 0, 5, true)), "bitcoin: bech32 invalid bits") { ok = false; }
  var over = Vec[Int].new();
  over.push(32);
  if !streq(ints_err(bech32_convertbits(&over, 5, 8, false)), "bitcoin: bech32 convertbits overflow") { ok = false; }
  // a single 5-bit symbol cannot convert to bytes without padding
  if !streq(bytes_err(bech32_symbols_to_bytes(&one)), "bitcoin: bech32 invalid padding") { ok = false; }
  return assert(ok, "bech32 rejections and convertbits errors");
}

// --------------------------------------------------
//  t18: SegWit address decoding (valid vectors)
// --------------------------------------------------

fn t18() -> TestResult {
  var ok = true;
  let wpkh = segwit_decode("bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4");
  if !wpkh.is_ok { ok = false; } else {
    let w: SegwitAddress = wpkh.value;
    let h: Str = segwit_hrp(&w);
    if !streq(h, "bc") { ok = false; }
    if segwit_witver(&w) != 0 { ok = false; }
    if !bytes_equal(segwit_program(&w), hb("751e76e8199196d454941c45d1b3a323f1433bd6")) { ok = false; }
  }
  // uppercase input folds to the lowercase HRP
  let up = segwit_decode("BC1QW508D6QEJXTDG4Y5R3ZARVARY0C5XW7KV8F3T4");
  if !up.is_ok { ok = false; } else {
    let w2: SegwitAddress = up.value;
    let h2: Str = segwit_hrp(&w2);
    if !streq(h2, "bc") { ok = false; }
    if !bytes_equal(segwit_program(&w2), hb("751e76e8199196d454941c45d1b3a323f1433bd6")) { ok = false; }
  }
  let wsh = segwit_decode("tb1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3q0sl5k7");
  if !wsh.is_ok { ok = false; } else {
    let w3: SegwitAddress = wsh.value;
    if segwit_witver(&w3) != 0 { ok = false; }
    if !bytes_equal(segwit_program(&w3), hb("1863143c14c5166804bd19203356da136c985678cd4d27a1b8c6329604903262")) { ok = false; }
  }
  let tr = segwit_decode("bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0");
  if !tr.is_ok { ok = false; } else {
    let w4: SegwitAddress = tr.value;
    if segwit_witver(&w4) != 1 { ok = false; }
    if !bytes_equal(segwit_program(&w4), hb("79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798")) { ok = false; }
  }
  // v1 with a 40-byte program (BIP-350 re-encoding of the BIP-173 vector)
  let p40 = segwit_decode("bc1pw508d6qejxtdg4y5r3zarvary0c5xw7kw508d6qejxtdg4y5r3zarvary0c5xw7kt5nd6y");
  if !p40.is_ok { ok = false; } else {
    let w5: SegwitAddress = p40.value;
    if segwit_witver(&w5) != 1 { ok = false; }
    if segwit_program(&w5).len() != 40 { ok = false; }
  }
  // v16 with a 2-byte program
  let v16 = segwit_decode("BC1SW50QGDZ25J");
  if !v16.is_ok { ok = false; } else {
    let w6: SegwitAddress = v16.value;
    if segwit_witver(&w6) != 16 { ok = false; }
    if !bytes_equal(segwit_program(&w6), hb("751e")) { ok = false; }
  }
  // v2 with a 16-byte program
  let v2 = segwit_decode("bc1zw508d6qejxtdg4y5r3zarvaryvaxxpcs");
  if !v2.is_ok { ok = false; } else {
    let w7: SegwitAddress = v2.value;
    if segwit_witver(&w7) != 2 { ok = false; }
    if !bytes_equal(segwit_program(&w7), hb("751e76e8199196d454941c45d1b3a323")) { ok = false; }
  }
  let taproot = segwit_decode("tb1pqqqqp399et2xygdj5xreqhjjvcmzhxw4aywxecjdzew6hylgvsesf3hn0c");
  if !taproot.is_ok { ok = false; } else {
    let w8: SegwitAddress = taproot.value;
    if !bytes_equal(segwit_program(&w8), hb("000000c4a5cad46221b2a187905e5266362b99d5e91c6ce24d165dab93e86433")) { ok = false; }
  }
  return assert(ok, "segwit address valid BIP-173/BIP-350 vectors");
}

// --------------------------------------------------
//  t19: SegWit address rejections and encoding
// --------------------------------------------------

fn t19() -> TestResult {
  var ok = true;
  if !streq(segwit_err(segwit_decode("bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kemeawh")), "bitcoin: bech32 wrong variant for witness v0") { ok = false; }
  if !streq(segwit_err(segwit_decode("bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqh2y7hd")), "bitcoin: bech32 wrong variant for witness v1+") { ok = false; }
  if !streq(segwit_err(segwit_decode("BC1SW50QA3JX3S")), "bitcoin: bech32 wrong variant for witness v1+") { ok = false; }
  if !streq(segwit_err(segwit_decode("bc1zw508d6qejxtdg4y5r3zarvaryvg6kdaj")), "bitcoin: bech32 wrong variant for witness v1+") { ok = false; }
  if !streq(segwit_err(segwit_decode("bc1pw5dgrnzv")), "bitcoin: bech32 witness program length out of range") { ok = false; }
  if !streq(segwit_err(segwit_decode("BC130XLXVLHEMJA6C4DQV22UAPCTQUPFHLXM9H8Z3K2E72Q4K9HCZ7VQ7ZWS8R")), "bitcoin: bech32 witness version out of range") { ok = false; }
  if !streq(segwit_err(segwit_decode("tb1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vq47Zagq")), "bitcoin: bech32 mixed case") { ok = false; }
  // encoding: the canonical lowercase forms
  let p20 = hb("751e76e8199196d454941c45d1b3a323f1433bd6");
  let e1 = segwit_encode("bc", 0, &p20);
  if !e1.is_ok { ok = false; } else {
    let s1: Str = e1.value;
    if !streq(s1, "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4") { ok = false; }
  }
  let p32 = hb("79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798");
  let e2 = segwit_encode("bc", 1, &p32);
  if !e2.is_ok { ok = false; } else {
    let s2: Str = e2.value;
    if !streq(s2, "bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0") { ok = false; }
  }
  // encoding errors
  if !streq(str_err(segwit_encode("bc", 17, &p32)), "bitcoin: bech32 witness version out of range") { ok = false; }
  let p1 = hb("75");
  if !streq(str_err(segwit_encode("bc", 1, &p1)), "bitcoin: bech32 witness program length out of range") { ok = false; }
  let p16 = hb("751e76e8199196d454941c45d1b3a323");
  if !streq(str_err(segwit_encode("bc", 0, &p16)), "bitcoin: bech32 bad witness v0 program length") { ok = false; }
  let p41 = rep_byte(7, 41);
  if !streq(str_err(segwit_encode("bc", 1, &p41)), "bitcoin: bech32 witness program length out of range") { ok = false; }
  return assert(ok, "segwit rejections (variants, versions, lengths) and encoding");
}

// --------------------------------------------------
//  t20: header writer, u64 helpers, writer edge cases
// --------------------------------------------------

fn t20() -> TestResult {
  var ok = true;
  var ck = hb("deadbeef");
  var o = Vec[UInt8].new();
  let w = message_header_write(&mut o, BITCOIN_MAGIC_MAINNET, "tx", 125, &ck);
  if !w.is_ok { ok = false; } else {
    let n: Int = w.value;
    if n != 24 { ok = false; }
  }
  let frame = frame_of("tx", legacy_tx_bytes(), "deadbeef");
  if !bytes_equal(o, prefix_of(frame, 24)) { ok = false; }
  // writer errors
  var e1 = Vec[UInt8].new();
  if !streq(int_err(message_header_write(&mut e1, -1, "tx", 0, &ck)), "bitcoin: magic out of range") { ok = false; }
  var e2 = Vec[UInt8].new();
  if !streq(int_err(message_header_write(&mut e2, 0, "tx", -1, &ck)), "bitcoin: payload length out of range") { ok = false; }
  var e3 = Vec[UInt8].new();
  let longcmd = string.str_repeat("a", 13);
  if !streq(int_err(message_header_write(&mut e3, 0, longcmd, 0, &ck)), "bitcoin: command longer than 12 bytes") { ok = false; }
  var e4 = Vec[UInt8].new();
  var ck3 = hb("deadbe");
  if !streq(int_err(message_header_write(&mut e4, 0, "tx", 0, &ck3)), "bitcoin: checksum must be 4 bytes") { ok = false; }
  // negative n writes nothing
  var e5 = Vec[UInt8].new();
  compact_size_write(&mut e5, -5);
  if e5.len() != 0 { ok = false; }
  var e6 = Vec[UInt8].new();
  varint_legacy_write(&mut e6, 253);
  if !bytes_equal(e6, hb("fdfd00")) { ok = false; }
  // u64 byte helpers
  if !bytes_equal(bitcoin_u64_le_bytes(9), hb("0900000000000000")) { ok = false; }
  if !bitcoin_u64_fits_int(&hb("ffffffffffffff7f")) { ok = false; }
  if bitcoin_u64_fits_int(&hb("0000000000000080")) { ok = false; }
  if bitcoin_u64_to_int(&hb("0100000000000000")) != 1 { ok = false; }
  return assert(ok, "header writer, writer edge cases and u64 helpers");
}

// --------------------------------------------------
//  Harness
// --------------------------------------------------

fn report(r: TestResult, failed: Int) -> Int {
  if r.passed {
    io.println("  [PASS] " + r.name);
    return failed;
  }
  io.println("  [FAIL] " + r.name);
  return failed + 1;
}

fn main() -> Int {
  io.println("=== xiom.bitcoin conformance tests ===");
  var failed: Int = 0;
  failed = report(t1(), failed);
  failed = report(t2(), failed);
  failed = report(t3(), failed);
  failed = report(t4(), failed);
  failed = report(t5(), failed);
  failed = report(t6(), failed);
  failed = report(t7(), failed);
  failed = report(t8(), failed);
  failed = report(t9(), failed);
  failed = report(t10(), failed);
  failed = report(t11(), failed);
  failed = report(t12(), failed);
  failed = report(t13(), failed);
  failed = report(t14(), failed);
  failed = report(t15(), failed);
  failed = report(t16(), failed);
  failed = report(t17(), failed);
  failed = report(t18(), failed);
  failed = report(t19(), failed);
  failed = report(t20(), failed);
  if failed == 0 {
    io.println("xiom.bitcoin: all tests passed");
  } else {
    io.println("xiom.bitcoin: tests failed");
  }
  return failed;
}
