// XIOM -- xiom.badger conformance tests (21 checks)
// Copyright (c) 2026 Eleftherios Notas and The XIOM Authors
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Covers the v1.6.2 byte-compatible API against synthetic buffers assembled
// in-test. Four fixtures are byte-for-byte outputs of the upstream v1.6.2
// code, generated by compiling dgraph-io/badger @ v1.6.2 with Go and embedded
// as hex/JSON text (no external data files at run time):
//   * VLOG_HEX: three value-log entries (plain, bitTxn, bitFinTxn) written
//     exactly per structs.go encodeEntry;
//   * MANIFEST_HEX + BODY1/BODY2: header "Bdgr"+4 and two records produced
//     by the real pb.ManifestChangeSet protobuf plus y.CastagnoliCrcTable;
//   * TABLE_SMALL_HEX: a 237-byte table emitted by table.NewTableBuilder()
//     with three entries (delete meta, value-pointer meta + expiry, plain),
//     its block index and its bbloom JSON envelope;
//   * TABLE_SMALL_SHA256: the digest v1.6.2 loadToRAM computes over the
//     table bytes.
// All other fixtures are assembled byte by byte in-test. The local CRC32C
// helper is written independently of the module (bit-serial reference).
// Str equality goes through str_compare (BUG 17 discipline: `==` on a Str
// read from a Vec lowers to a pointer comparison).

module badger_tests
use xiom.io; use xiom.test;
use xiom.badger;
use xiom.string;
use xiom.string.compare;

// --------------------------------------------------
//  Generic test helpers
// --------------------------------------------------

fn str_eq(a: Str, b: Str) -> Bool {
  return compare.str_compare(a, b) == 0;
}

fn int_is(r: Result[Int, Str], want: Int) -> Bool {
  if !r.is_ok { return false; }
  let v: Int = r.value;
  return v == want;
}

fn bool_is(r: Result[Bool, Str], want: Bool) -> Bool {
  if !r.is_ok { return false; }
  let v: Bool = r.value;
  if v == want { return true; }
  return false;
}

fn err_int_is(r: Result[Int, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_bool_is(r: Result[Bool, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_vp_is(r: Result[BadgerValuePointer, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_key_is(r: Result[BadgerKey, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_vh_is(r: Result[BadgerVlogHeader, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_vwalk_is(r: Result[BadgerVlogWalk, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_vs_is(r: Result[BadgerSstValStruct, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_sse_list_is(r: Result[BadgerSstEntries, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_idx_is(r: Result[BadgerSstIndex, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_tail_is(r: Result[BadgerSstTail, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_bloom_is(r: Result[BadgerBloom, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_mh_is(r: Result[BadgerManifestHeader, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_mrecs_is(r: Result[BadgerManifestRecords, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_mrec_is(r: Result[BadgerManifestRecord, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_mch_is(r: Result[BadgerManifestChanges, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn err_mt_is(r: Result[BadgerManifestTables, Str], want: Str) -> Bool {
  if r.is_ok { return false; }
  return str_eq(r.error, want);
}

fn bytes_eq(a: &Vec[UInt8], b: &Vec[UInt8]) -> Bool {
  if a.len() != b.len() { return false; }
  var i = 0;
  while i < a.len() {
    let x: UInt8 = a[i];
    let y: UInt8 = b[i];
    if x != y { return false; }
    i = i + 1;
  }
  return true;
}

// --------------------------------------------------
//  Byte helpers (independent of src/badger.xi)
// --------------------------------------------------

fn gb(data: &Vec[UInt8], pos: Int) -> Int {
  return (data[pos] as Int) & 0xFF;
}

fn text(s: Str) -> Vec[UInt8] {
  var v = Vec[UInt8].new();
  push_text(&mut v, s);
  return v;
}

fn push_text(dst: &mut Vec[UInt8], s: Str) {
  var i = 0;
  while i < s.len() {
    dst.push(string.byte_at(s, i));
    i = i + 1;
  }
  return;
}

fn append_bytes(dst: &mut Vec[UInt8], src: &Vec[UInt8]) {
  var i = 0;
  while i < src.len() {
    let b: UInt8 = src[i];
    dst.push(b);
    i = i + 1;
  }
  return;
}

fn push_be16(dst: &mut Vec[UInt8], v: Int) {
  dst.push(((v / 256) % 256) as UInt8);
  dst.push((v % 256) as UInt8);
  return;
}

fn push_be32(dst: &mut Vec[UInt8], v: Int) {
  push_be16(dst, v / 65536);
  push_be16(dst, v % 65536);
  return;
}

fn push_be64(dst: &mut Vec[UInt8], v: Int) {
  push_be32(dst, v / 4294967296);
  push_be32(dst, v % 4294967296);
  return;
}

// The big-endian 8-byte suffix MaxUint64 - ts, i.e. the bitwise complement of
// ts for every ts a real Badger writes. Built without 64-bit negatives.
fn push_ts_suffix(dst: &mut Vec[UInt8], ts: Int) {
  var j = 7;
  while j >= 0 {
    let shift = 8 * j;
    let byte_val = (ts / pow2_local(shift)) % 256;
    dst.push((255 - byte_val) as UInt8);
    j = j - 1;
  }
  return;
}

fn pow2_local(k: Int) -> Int {
  var p = 1;
  var i = 0;
  while i < k {
    p = p * 2;
    i = i + 1;
  }
  return p;
}

fn versioned_key(user: Str, ts: Int) -> Vec[UInt8] {
  var v = Vec[UInt8].new();
  push_text(&mut v, user);
  push_ts_suffix(&mut v, ts);
  return v;
}

fn slice_of(src: &Vec[UInt8], start: Int, size: Int) -> Vec[UInt8] {
  var v = Vec[UInt8].new();
  var i = 0;
  while i < size {
    let b: UInt8 = src[start + i];
    v.push(b);
    i = i + 1;
  }
  return v;
}

fn set_at(src: &Vec[UInt8], pos: Int, val: Int) -> Vec[UInt8] {
  var v = Vec[UInt8].new();
  var i = 0;
  while i < src.len() {
    if i == pos {
      v.push((val as UInt8));
    } else {
      let b: UInt8 = src[i];
      v.push(b);
    }
    i = i + 1;
  }
  return v;
}

fn nibble_of(s: Str, pos: Int) -> Int {
  let b: Int = (string.byte_at(s, pos) as Int) & 255;
  if b >= 48 && b <= 57 { return b - 48; }
  if b >= 97 && b <= 102 { return b - 87; }
  if b >= 65 && b <= 70 { return b - 55; }
  return 0;
}

fn hex_bytes(s: Str) -> Vec[UInt8] {
  var v = Vec[UInt8].new();
  var i = 0;
  while i + 1 < s.len() {
    let hi = nibble_of(s, i);
    let lo = nibble_of(s, i + 1);
    v.push(((hi * 16 + lo) as UInt8));
    i = i + 2;
  }
  return v;
}

// Independent bit-serial CRC32C (Castagnoli, reflected) reference.
fn crc_step_local(crc_in: Int, b: Int) -> Int {
  var crc = crc_in ^ b;
  var k = 0;
  while k < 8 {
    let lsb = crc % 2;
    crc = crc / 2;
    if lsb == 1 {
      crc = crc ^ 2197175160;
    }
    k = k + 1;
  }
  return crc;
}

fn crc_local(data: &Vec[UInt8], start: Int, size: Int) -> Int {
  var crc = 4294967295;
  var i = 0;
  while i < size {
    crc = crc_step_local(crc, gb(data, start + i));
    i = i + 1;
  }
  return (crc ^ 4294967295) & 4294967295;
}

// --------------------------------------------------
//  Embedded upstream v1.6.2 fixtures (see file header)
// --------------------------------------------------

fn fx_vlog() -> Vec[UInt8] {
  return hex_bytes("0000000d0000000300000000000000000009616c706861fffffffffffffffa6f6e651dc8cbe80000000c00000002000000000000004d400062657461fffffffffffffff9747895b889b30000000c000000010000000000000000800062657461fffffffffffffff9366cb0c910");
}

fn fx_manifest() -> Vec[UInt8] {
  return hex_bytes("42646772000000040000004ed05089090a26080118022220000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f0a2408022220000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f000000067860398f0a0408021001");
}

fn fx_manifest_body1() -> Vec[UInt8] {
  return hex_bytes("0a26080118022220000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f0a2408022220000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f");
}

fn fx_manifest_body2() -> Vec[UInt8] {
  return hex_bytes("0a0408021001");
}

fn fx_table_small() -> Vec[UInt8] {
  return hex_bytes("0000000d0006ffffffff6170706c65ffffffffffffff9b0007007265640002000d000b000000007269636f74ffffffffffffffa50200b5b8f0fe2d090807060000000e00090000001d62616e616e61ffffffffffffffaf01000079656c6c6f770000000000030000003f0000000000006d000000017b2246696c746572536574223a2251414567414141514141414941414545414541434141424241414541414141414141414141414541514141414145414141424141414141414141414141424241414141415141414141424141414141414141414151413d3d222c225365744c6f6373223a377d00000074");
}

fn fx_table_small_sha256() -> Str {
  return "e14839d3208fb5870b0fec9032d5bb69f8101d200045b293fbc9a3c6d18ee938";
}

fn zeros(n: Int) -> Vec[UInt8] {
  var v = Vec[UInt8].new();
  var i = 0;
  while i < n {
    v.push(0);
    i = i + 1;
  }
  return v;
}

// --------------------------------------------------
//  t1: CRC32C known answers
// --------------------------------------------------

fn t1() -> TestResult {
  let name = "CRC32C known answers and reference agreement";
  var ok = true;
  let empty = Vec[UInt8].new();
  if badger_crc32c(&empty, 0, 0) != 0 { ok = false; }
  let digits = text("123456789");
  if badger_crc32c(&digits, 0, 9) != 3808858755 { ok = false; }
  let z32 = zeros(32);
  if badger_crc32c(&z32, 0, 32) != 2324772522 { ok = false; }
  var f32 = Vec[UInt8].new();
  var i = 0;
  while i < 32 {
    f32.push(255);
    i = i + 1;
  }
  if badger_crc32c(&f32, 0, 32) != 1655221059 { ok = false; }
  var asc = Vec[UInt8].new();
  i = 0;
  while i < 32 {
    asc.push((i as UInt8));
    i = i + 1;
  }
  if badger_crc32c(&asc, 0, 32) != 1188919630 { ok = false; }
  var desc = Vec[UInt8].new();
  i = 31;
  while i >= 0 {
    desc.push((i as UInt8));
    i = i - 1;
  }
  if badger_crc32c(&desc, 0, 32) != 289397596 { ok = false; }
  if badger_crc32c(&digits, 3, 7) != -1 { ok = false; }
  if badger_crc32c(&digits, 2, 7) != crc_local(&digits, 2, 7) { ok = false; }
  var mixed = Vec[UInt8].new();
  i = 0;
  while i < 256 {
    mixed.push(((i * 7 + 3) % 256) as UInt8);
    i = i + 1;
  }
  if badger_crc32c(&mixed, 0, 256) != crc_local(&mixed, 0, 256) { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t2: value log header on the real upstream entry
// --------------------------------------------------

fn t2() -> TestResult {
  let name = "vlog header: 18-byte BE fields from upstream bytes";
  var ok = true;
  let v = fx_vlog();
  if v.len() != 109 { ok = false; }
  let hr = badger_parse_vlog_header(&v, 0);
  if !hr.is_ok {
    ok = false;
  } else {
    let h = hr.value;
    if h.key_len != 13 { ok = false; }
    if h.val_len != 3 { ok = false; }
    if h.expires_at != 0 { ok = false; }
    if h.meta != 0 { ok = false; }
    if h.user_meta != 9 { ok = false; }
    if badger_vlog_entry_total(&h) != 38 { ok = false; }
  }
  let hr2 = badger_parse_vlog_header(&v, 38);
  if !hr2.is_ok {
    ok = false;
  } else {
    let h2 = hr2.value;
    if h2.key_len != 12 { ok = false; }
    if h2.val_len != 2 { ok = false; }
    if h2.expires_at != 77 { ok = false; }
    if h2.meta != 64 { ok = false; }
    if badger_vlog_entry_total(&h2) != 36 { ok = false; }
  }
  if !int_is(badger_vlog_entry_crc(&v, 0), 499698664) { ok = false; }
  if !bool_is(badger_vlog_entry_crc_ok(&v, 0), true) { ok = false; }
  if !bool_is(badger_vlog_entry_crc_ok(&v, 38), true) { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t3: multi-entry walk over the real upstream entries
// --------------------------------------------------

fn t3() -> TestResult {
  let name = "vlog walk: spans, metas, CRCs and totals";
  var ok = true;
  let v = fx_vlog();
  let wr = badger_vlog_walk(&v, 0, v.len(), 16);
  if !wr.is_ok {
    ok = false;
  } else {
    let w = wr.value;
    if badger_vlog_count(&w) != 3 { ok = false; }
    if w.total_bytes != 109 { ok = false; }
    if !int_is(badger_vlog_field(&w, 0, BADGER_VLOG_FIELD_OFFSET), 0) { ok = false; }
    if !int_is(badger_vlog_field(&w, 1, BADGER_VLOG_FIELD_OFFSET), 38) { ok = false; }
    if !int_is(badger_vlog_field(&w, 2, BADGER_VLOG_FIELD_OFFSET), 74) { ok = false; }
    if !int_is(badger_vlog_field(&w, 0, BADGER_VLOG_FIELD_KEY_SIZE), 13) { ok = false; }
    if !int_is(badger_vlog_field(&w, 1, BADGER_VLOG_FIELD_KEY_SIZE), 12) { ok = false; }
    if !int_is(badger_vlog_field(&w, 2, BADGER_VLOG_FIELD_KEY_SIZE), 12) { ok = false; }
    if !int_is(badger_vlog_field(&w, 0, BADGER_VLOG_FIELD_VALUE_SIZE), 3) { ok = false; }
    if !int_is(badger_vlog_field(&w, 1, BADGER_VLOG_FIELD_VALUE_SIZE), 2) { ok = false; }
    if !int_is(badger_vlog_field(&w, 2, BADGER_VLOG_FIELD_VALUE_SIZE), 1) { ok = false; }
    if !int_is(badger_vlog_field(&w, 0, BADGER_VLOG_FIELD_META), 0) { ok = false; }
    if !int_is(badger_vlog_field(&w, 1, BADGER_VLOG_FIELD_META), 64) { ok = false; }
    if !int_is(badger_vlog_field(&w, 2, BADGER_VLOG_FIELD_META), 128) { ok = false; }
    if !int_is(badger_vlog_field(&w, 0, BADGER_VLOG_FIELD_USER_META), 9) { ok = false; }
    if !int_is(badger_vlog_field(&w, 1, BADGER_VLOG_FIELD_EXPIRES_AT), 77) { ok = false; }
    if !int_is(badger_vlog_field(&w, 0, BADGER_VLOG_FIELD_CRC), 499698664) { ok = false; }
    if !int_is(badger_vlog_field(&w, 0, BADGER_VLOG_FIELD_COUNT), 3) { ok = false; }
    let k0 = badger_vlog_key_bytes(&v, &w, 0);
    if !bytes_eq(&k0, &versioned_key("alpha", 5)) { ok = false; }
    let v0 = badger_vlog_value_bytes(&v, &w, 0);
    if !bytes_eq(&v0, &text("one")) { ok = false; }
    let v1 = badger_vlog_value_bytes(&v, &w, 1);
    if !bytes_eq(&v1, &text("tx")) { ok = false; }
    let v2 = badger_vlog_value_bytes(&v, &w, 2);
    if !bytes_eq(&v2, &text("6")) { ok = false; }
    if !err_int_is(badger_vlog_field(&w, 3, BADGER_VLOG_FIELD_META), "badger: vlog field index out of range at 3") { ok = false; }
  }
  return assert(ok, name);
}

// --------------------------------------------------
//  t4: upstream transaction grouping
// --------------------------------------------------

fn t4() -> TestResult {
  let name = "vlog txn prefix: grouped bitTxn/bitFinTxn replay";
  var ok = true;
  let v = fx_vlog();
  let wr = badger_vlog_walk(&v, 0, v.len(), 16);
  if !wr.is_ok {
    ok = false;
  } else {
    let w = wr.value;
    let t = badger_vlog_txn_prefix(&v, &w);
    if t.valid_entries != 3 { ok = false; }
    if t.groups != 1 { ok = false; }
    if t.closed != true { ok = false; }
    if !str_eq(t.reason, "") { ok = false; }
  }
  // Without the terminator: plain entry committed, txn group still open.
  let wr2 = badger_vlog_walk(&v, 0, 74, 16);
  if !wr2.is_ok {
    ok = false;
  } else {
    let w2 = wr2.value;
    let t2 = badger_vlog_txn_prefix(&v, &w2);
    if t2.valid_entries != 1 { ok = false; }
    if t2.groups != 0 { ok = false; }
    if t2.closed { ok = false; }
    if !str_eq(t2.reason, "unclosed txn group") { ok = false; }
  }
  // A group alone still commits: txn entry then its terminator.
  let wr3 = badger_vlog_walk(&v, 38, 109, 16);
  if !wr3.is_ok {
    ok = false;
  } else {
    let w3 = wr3.value;
    let tt3 = badger_vlog_txn_prefix(&v, &w3);
    if tt3.valid_entries != 2 { ok = false; }
    if tt3.groups != 1 { ok = false; }
    if tt3.closed != true { ok = false; }
  }
  return assert(ok, name);
}

// --------------------------------------------------
//  t5: value log structural errors and caps
// --------------------------------------------------

fn t5() -> TestResult {
  let name = "vlog errors: caps, bounds, CRC and max entries";
  var ok = true;
  // Value length above the local 1 MiB cap (1048577 = 0x00100001).
  var big_val = zeros(4);
  push_be32(&mut big_val, 1048577);
  append_bytes(&mut big_val, &zeros(10));
  if !err_vh_is(badger_parse_vlog_header(&big_val, 0), "badger: vlog value length exceeds cap at 4") { ok = false; }
  // Key length above the upstream 65536 bound (65537 = 0x00010001).
  var big_key = Vec[UInt8].new();
  push_be32(&mut big_key, 65537);
  append_bytes(&mut big_key, &zeros(14));
  if !err_vh_is(badger_parse_vlog_header(&big_key, 0), "badger: vlog key length exceeds upstream bound at 0") { ok = false; }
  let v = fx_vlog();
  let short = slice_of(&v, 0, 17);
  if !err_vh_is(badger_parse_vlog_header(&short, 0), "badger: vlog header truncated at 0") { ok = false; }
  var padded = Vec[UInt8].new();
  append_bytes(&mut padded, &v);
  append_bytes(&mut padded, &zeros(5));
  if !err_vwalk_is(badger_vlog_walk(&padded, 0, padded.len(), 16), "badger: vlog walk trailing bytes at 109") { ok = false; }
  let corrupt = set_at(&v, 18, gb(&v, 18) ^ 255);
  if !err_vwalk_is(badger_vlog_walk(&corrupt, 0, corrupt.len(), 16), "badger: vlog entry crc mismatch at 0") { ok = false; }
  if !bool_is(badger_vlog_entry_crc_ok(&corrupt, 0), false) { ok = false; }
  if !err_vwalk_is(badger_vlog_walk(&v, 0, v.len(), 2), "badger: vlog walk exceeds max entries at 74") { ok = false; }
  if !err_vwalk_is(badger_vlog_walk(&v, 10, 5, 2), "badger: vlog walk limit before start at 5") { ok = false; }
  if !err_vwalk_is(badger_vlog_walk(&v, 0, v.len(), 0), "badger: vlog walk max entries must be positive at 0") { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t6: meta bit table (v1.6.2 value.go)
// --------------------------------------------------

fn t6() -> TestResult {
  let name = "meta bits: upstream table, names and known/unknown";
  var ok = true;
  if !str_eq(badger_meta_bit_name(1), "DELETE") { ok = false; }
  if !str_eq(badger_meta_bit_name(2), "VALUE_POINTER") { ok = false; }
  if !str_eq(badger_meta_bit_name(4), "DISCARD_EARLIER_VERSIONS") { ok = false; }
  if !str_eq(badger_meta_bit_name(8), "MERGE_ENTRY") { ok = false; }
  if !str_eq(badger_meta_bit_name(64), "TXN") { ok = false; }
  if !str_eq(badger_meta_bit_name(128), "FIN_TXN") { ok = false; }
  if !str_eq(badger_meta_bit_name(16), "") { ok = false; }
  if !str_eq(badger_meta_names(66), "VALUE_POINTER|TXN") { ok = false; }
  if !str_eq(badger_meta_names(1), "DELETE") { ok = false; }
  if !str_eq(badger_meta_names(0), "") { ok = false; }
  if !str_eq(badger_meta_names(207), "DELETE|VALUE_POINTER|DISCARD_EARLIER_VERSIONS|MERGE_ENTRY|TXN|FIN_TXN") { ok = false; }
  if badger_meta_known(207) != true { ok = false; }
  if badger_meta_known(255) { ok = false; }
  if badger_meta_known(16) { ok = false; }
  if badger_meta_known(0) != true { ok = false; }
  if badger_meta_has(66, 64) != true { ok = false; }
  if badger_meta_has(66, 2) != true { ok = false; }
  if badger_meta_has(66, 1) { ok = false; }
  if badger_meta_has(1, 0) { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t7: versioned keys, MaxUint64 - ts suffix
// --------------------------------------------------

fn t7() -> TestResult {
  let name = "keys: BE MaxUint64-ts suffix, version and user spans";
  var ok = true;
  let v = fx_vlog();
  let k0 = slice_of(&v, 18, 13);
  let kr = badger_key_decode(&k0, 0, 13);
  if !kr.is_ok {
    ok = false;
  } else {
    let k = kr.value;
    if badger_key_user_size(&k) != 5 { ok = false; }
    if badger_key_version(&k) != 5 { ok = false; }
    if badger_key_tagged(&k) != -6 { ok = false; }
    let ub = badger_key_user_bytes(&k0, &k);
    if !bytes_eq(&ub, &text("alpha")) { ok = false; }
  }
  let k1 = slice_of(&v, 56, 12);
  let kr1 = badger_key_decode(&k1, 0, 12);
  if !kr1.is_ok {
    ok = false;
  } else {
    let kk = kr1.value;
    if badger_key_version(&kk) != 6 { ok = false; }
    let ub1 = badger_key_user_bytes(&k1, &kk);
    if !bytes_eq(&ub1, &text("beta")) { ok = false; }
  }
  if badger_key_parse_ts(&k0, 0, 13) != 5 { ok = false; }
  if badger_key_parse_ts(&k0, 0, 8) != 0 { ok = false; }
  if !err_key_is(badger_key_decode(&k0, 0, 8), "badger: key shorter than version tag at 0") { ok = false; }
  if !err_key_is(badger_key_decode(&k0, 0, 20), "badger: key span out of bounds at 0") { ok = false; }
  if !err_key_is(badger_key_decode(&k0, -1, 13), "badger: key span out of bounds at 0") { ok = false; }
  // Encode side: versioned_key builds the same bytes upstream KeyWithTs does.
  let want = versioned_key("alpha", 5);
  if gb(&want, 5) != 255 { ok = false; }
  if gb(&want, 12) != 250 { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t8: value pointers (structs.go valuePointer)
// --------------------------------------------------

fn t8() -> TestResult {
  let name = "value pointer: 12-byte BE fid/len/offset";
  var ok = true;
  var vp = Vec[UInt8].new();
  push_be32(&mut vp, 7);
  push_be32(&mut vp, 1234);
  push_be32(&mut vp, 98765);
  let pr = badger_value_pointer_decode(&vp, 0);
  if !pr.is_ok {
    ok = false;
  } else {
    let p = pr.value;
    if p.fid != 7 { ok = false; }
    if p.len != 1234 { ok = false; }
    if p.offset != 98765 { ok = false; }
  }
  let short = zeros(11);
  if !err_vp_is(badger_value_pointer_decode(&short, 0), "badger: value pointer truncated at 0") { ok = false; }
  if !err_vp_is(badger_value_pointer_decode(&vp, -1), "badger: value pointer out of bounds at 0") { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t9: SST block entries and ValueStructs (upstream bytes)
// --------------------------------------------------

fn t9() -> TestResult {
  let name = "sst entries: 10-byte BE header and ValueStruct decode";
  var ok = true;
  let tbl = fx_table_small();
  let block = slice_of(&tbl, 0, 109);
  let empty = Vec[UInt8].new();
  let e0r = badger_parse_sst_block_entry(&block, 0, 109, &empty);
  if !e0r.is_ok {
    ok = false;
  } else {
    let e0 = e0r.value;
    if e0.plen != 0 { ok = false; }
    if e0.klen != 13 { ok = false; }
    if e0.vlen != 6 { ok = false; }
    if e0.prev != BADGER_SST_ENTRY_PREV_NONE { ok = false; }
    if e0.entry_bytes != 29 { ok = false; }
    if !bytes_eq(&e0.key, &versioned_key("apple", 100)) { ok = false; }
    let vsr = badger_sst_value_struct_decode(&block, e0.value_offset, e0.vlen);
    if !vsr.is_ok {
      ok = false;
    } else {
      let vs = vsr.value;
      if vs.meta != 0 { ok = false; }
      if vs.user_meta != 7 { ok = false; }
      if vs.expires_at != 0 { ok = false; }
      if vs.value_size != 3 { ok = false; }
      if gb(&block, vs.value_offset) != 114 { ok = false; }
    }
  }
  let base = versioned_key("apple", 100);
  let e1r = badger_parse_sst_block_entry(&block, 29, 109, &base);
  if !e1r.is_ok {
    ok = false;
  } else {
    let e1 = e1r.value;
    if e1.plen != 2 { ok = false; }
    if e1.klen != 13 { ok = false; }
    if e1.vlen != 11 { ok = false; }
    if e1.prev != 0 { ok = false; }
    if e1.entry_bytes != 34 { ok = false; }
    if !bytes_eq(&e1.key, &versioned_key("apricot", 90)) { ok = false; }
    let vs1r = badger_sst_value_struct_decode(&block, e1.value_offset, e1.vlen);
    if !vs1r.is_ok {
      ok = false;
    } else {
      let vs1 = vs1r.value;
      if vs1.meta != 2 { ok = false; }
      if vs1.expires_at != 12345678901 { ok = false; }
      if vs1.value_size != 4 { ok = false; }
      if gb(&block, vs1.value_offset) != 9 { ok = false; }
      if gb(&block, vs1.value_offset + 3) != 6 { ok = false; }
    }
  }
  let e2r = badger_parse_sst_block_entry(&block, 63, 109, &base);
  if !e2r.is_ok {
    ok = false;
  } else {
    let e2 = e2r.value;
    if e2.plen != 0 { ok = false; }
    if e2.klen != 14 { ok = false; }
    if e2.vlen != 9 { ok = false; }
    if e2.prev != 29 { ok = false; }
    if !bytes_eq(&e2.key, &versioned_key("banana", 80)) { ok = false; }
    let vs2r = badger_sst_value_struct_decode(&block, e2.value_offset, e2.vlen);
    if !vs2r.is_ok {
      ok = false;
    } else {
      let vs2 = vs2r.value;
      if vs2.meta != 1 { ok = false; }
      if vs2.user_meta != 0 { ok = false; }
      if vs2.value_size != 6 { ok = false; }
    }
  }
  if !err_sse_list_is(badger_sst_block_walk(&block, 8), "badger: sst entry header truncated at 0") { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t10: SST data-block walk
// --------------------------------------------------

fn t10() -> TestResult {
  let name = "sst block walk: reconstruction, terminator, fields";
  var ok = true;
  let tbl = fx_table_small();
  let block = slice_of(&tbl, 0, 109);
  let wr = badger_sst_block_walk(&block, 109);
  if !wr.is_ok {
    ok = false;
  } else {
    let w = wr.value;
    if badger_sst_block_count(&w) != 3 { ok = false; }
    if badger_sst_block_entries_end(&w) != 96 { ok = false; }
    if !int_is(badger_sst_block_field(&w, 0, BADGER_SST_FIELD_ENTRY_OFFSET), 0) { ok = false; }
    if !int_is(badger_sst_block_field(&w, 1, BADGER_SST_FIELD_ENTRY_OFFSET), 29) { ok = false; }
    if !int_is(badger_sst_block_field(&w, 2, BADGER_SST_FIELD_ENTRY_OFFSET), 63) { ok = false; }
    if !int_is(badger_sst_block_field(&w, 0, BADGER_SST_FIELD_PLEN), 0) { ok = false; }
    if !int_is(badger_sst_block_field(&w, 1, BADGER_SST_FIELD_PLEN), 2) { ok = false; }
    if !int_is(badger_sst_block_field(&w, 1, BADGER_SST_FIELD_VALUE_OFFSET), 52) { ok = false; }
    if !int_is(badger_sst_block_field(&w, 1, BADGER_SST_FIELD_VALUE_SIZE), 11) { ok = false; }
    if !int_is(badger_sst_block_field(&w, 1, BADGER_SST_FIELD_PREV), 0) { ok = false; }
    if !int_is(badger_sst_block_field(&w, 0, BADGER_SST_FIELD_PREV), BADGER_SST_ENTRY_PREV_NONE) { ok = false; }
    if !int_is(badger_sst_block_field(&w, 0, BADGER_SST_FIELD_COUNT), 3) { ok = false; }
    let k0 = badger_sst_block_key(&w, 0);
    if !bytes_eq(&k0, &versioned_key("apple", 100)) { ok = false; }
    let k1 = badger_sst_block_key(&w, 1);
    if !bytes_eq(&k1, &versioned_key("apricot", 90)) { ok = false; }
    let k2 = badger_sst_block_key(&w, 2);
    if !bytes_eq(&k2, &versioned_key("banana", 80)) { ok = false; }
    let val1 = badger_sst_block_value(&block, &w, 1);
    if val1.len() != 11 { ok = false; }
    if !err_int_is(badger_sst_block_field(&w, 3, BADGER_SST_FIELD_PLEN), "badger: sst field index out of range at 3") { ok = false; }
  }
  // A malformed block whose first entry has a nonzero prefix.
  var bad = Vec[UInt8].new();
  push_be16(&mut bad, 3);
  push_be16(&mut bad, 1);
  push_be16(&mut bad, 0);
  push_be32(&mut bad, 4294967295);
  bad.push(65);
  if !err_sse_list_is(badger_sst_block_walk(&bad, bad.len()), "badger: sst block first entry prefix nonzero at 0") { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t11: SST block index
// --------------------------------------------------

fn t11() -> TestResult {
  let name = "sst index: offsets, count, spans and bounds";
  var ok = true;
  let tbl = fx_table_small();
  let ixr = badger_sst_index_parse(&tbl, 109, 8);
  if !ixr.is_ok {
    ok = false;
  } else {
    let ix = ixr.value;
    if badger_sst_index_count(&ix) != 1 { ok = false; }
    if !int_is(badger_sst_index_block_end(&ix, 0), 109) { ok = false; }
    if !int_is(badger_sst_index_block_start(&ix, 0), 0) { ok = false; }
    if !int_is(badger_sst_index_block_size(&ix, 0), 109) { ok = false; }
    if !err_int_is(badger_sst_index_block_end(&ix, 1), "badger: sst index block out of range at 1") { ok = false; }
  }
  // Synthetic two-block index: ends 50 and 130.
  var two = Vec[UInt8].new();
  push_be32(&mut two, 50);
  push_be32(&mut two, 130);
  push_be32(&mut two, 2);
  let ix2r = badger_sst_index_parse(&two, 0, 12);
  if !ix2r.is_ok {
    ok = false;
  } else {
    let ix2 = ix2r.value;
    if badger_sst_index_count(&ix2) != 2 { ok = false; }
    if !int_is(badger_sst_index_block_start(&ix2, 1), 50) { ok = false; }
    if !int_is(badger_sst_index_block_size(&ix2, 1), 80) { ok = false; }
  }
  // Non-monotonic offsets.
  var bad = Vec[UInt8].new();
  push_be32(&mut bad, 130);
  push_be32(&mut bad, 50);
  push_be32(&mut bad, 2);
  if !err_idx_is(badger_sst_index_parse(&bad, 0, 12), "badger: sst index block offsets not monotonic at 4") { ok = false; }
  if !err_idx_is(badger_sst_index_parse(&bad, 0, 9), "badger: sst index size mismatch at 0") { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t12: SST file tail (no header, no footer in v1.6.2)
// --------------------------------------------------

fn t12() -> TestResult {
  let name = "sst tail: bloom length last, index before bloom";
  var ok = true;
  let tbl = fx_table_small();
  let tr = badger_sst_tail_parse(&tbl);
  if !tr.is_ok {
    ok = false;
  } else {
    let t = tr.value;
    if t.file_size != 237 { ok = false; }
    if t.index_offset != 109 { ok = false; }
    if t.index_size != 8 { ok = false; }
    if t.index_count != 1 { ok = false; }
    if t.bloom_offset != 117 { ok = false; }
    if t.bloom_size != 116 { ok = false; }
    let ixr = badger_sst_index_parse(&tbl, t.index_offset, t.index_size);
    if !ixr.is_ok { ok = false; }
    let br = badger_bloom_parse(&tbl, t.bloom_offset, t.bloom_size);
    if !br.is_ok { ok = false; }
  }
  let tiny = zeros(4);
  if !err_tail_is(badger_sst_tail_parse(&tiny), "badger: sst file too short for tail at 0") { ok = false; }
  var bad = Vec[UInt8].new();
  push_be32(&mut bad, 3);
  push_be32(&mut bad, 1000);
  if !err_tail_is(badger_sst_tail_parse(&bad), "badger: sst bloom length out of bounds at 4") { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t13: bloom filter envelope and membership
// --------------------------------------------------

fn t13() -> TestResult {
  let name = "bloom: bbloom JSON envelope, SipHash membership";
  var ok = true;
  let tbl = fx_table_small();
  let br = badger_bloom_parse(&tbl, 117, 116);
  if !br.is_ok {
    ok = false;
  } else {
    let b = br.value;
    if b.set_locs != 7 { ok = false; }
    if b.byte_count != 64 { ok = false; }
    if b.exponent != 9 { ok = false; }
    if b.filter_set_size != 88 { ok = false; }
    if gb(&tbl, b.filter_set_offset) != 81 { ok = false; }
    let apple = text("apple");
    let apricot = text("apricot");
    let banana = text("banana");
    let cherry = text("cherry");
    let a = text("a");
    if !bool_is(badger_bloom_has(&apple, &b, 0, 5), true) { ok = false; }
    if !bool_is(badger_bloom_has(&apricot, &b, 0, 7), true) { ok = false; }
    if !bool_is(badger_bloom_has(&banana, &b, 0, 6), true) { ok = false; }
    if !bool_is(badger_bloom_has(&cherry, &b, 0, 6), false) { ok = false; }
    if !bool_is(badger_bloom_has(&a, &b, 0, 1), false) { ok = false; }
    // Raw bit access: the first FilterSet byte decodes to 0x40 (bit 6 set).
    if !bool_is(badger_bloom_bit(&b, 6), true) { ok = false; }
    if !bool_is(badger_bloom_bit(&b, 0), false) { ok = false; }
    if !err_bool_is(badger_bloom_bit(&b, 512), "badger: bloom bit index out of range at 512") { ok = false; }
    if !err_bool_is(badger_bloom_has(&a, &b, 5, 1), "badger: bloom key out of bounds at 5") { ok = false; }
  }
  return assert(ok, name);
}

// --------------------------------------------------
//  t14: bloom filter malformed envelopes
// --------------------------------------------------

fn t14() -> TestResult {
  let name = "bloom errors: missing fields, bad base64, bad locs";
  var ok = true;
  let empty_json = text("{}");
  if !err_bloom_is(badger_bloom_parse(&empty_json, 0, 2), "badger: bloom filter set missing at 0") { ok = false; }
  let bad_b64 = text("{\"FilterSet\":\"AAA\",\"SetLocs\":7}");
  if !err_bloom_is(badger_bloom_parse(&bad_b64, 0, bad_b64.len()), "badger: bloom filter set: bad base64 length at 14") { ok = false; }
  let b64 = "QAEgAAAQAAAIAAEEAEACAABBAAEAAAAAAAAAAAEAQAAAAEAAABAAAAAAAAAAABBAAAAAQAAAABAAAAAAAAAAQA==";
  let no_locs = text("{\"FilterSet\":\"" + b64 + "\"}");
  if !err_bloom_is(badger_bloom_parse(&no_locs, 0, no_locs.len()), "badger: bloom set locs missing at 0") { ok = false; }
  let zero_locs = text("{\"FilterSet\":\"" + b64 + "\",\"SetLocs\":0}");
  let zr = badger_bloom_parse(&zero_locs, 0, zero_locs.len());
  if zr.is_ok { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t15: whole-table SHA-256 checksum
// --------------------------------------------------

fn t15() -> TestResult {
  let name = "sst checksum: SHA-256 KATs and upstream table digest";
  var ok = true;
  let empty = Vec[UInt8].new();
  if !str_eq(badger_sst_checksum_hex(&empty), "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855") { ok = false; }
  let abc = text("abc");
  if !str_eq(badger_sst_checksum_hex(&abc), "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad") { ok = false; }
  let tbl = fx_table_small();
  if !str_eq(badger_sst_checksum_hex(&tbl), fx_table_small_sha256()) { ok = false; }
  let digest = badger_sst_checksum(&tbl);
  if digest.len() != 32 { ok = false; }
  let want = hex_bytes(fx_table_small_sha256());
  if badger_sst_checksum_ok(&tbl, &want) != true { ok = false; }
  let wrong = set_at(&want, 0, gb(&want, 0) ^ 255);
  if badger_sst_checksum_ok(&tbl, &wrong) { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t16: manifest header
// --------------------------------------------------

fn t16() -> TestResult {
  let name = "manifest header: Bdgr + version 4";
  var ok = true;
  let m = fx_manifest();
  let hr = badger_manifest_header_parse(&m);
  if !hr.is_ok {
    ok = false;
  } else {
    let h = hr.value;
    if h.magic != BADGER_MANIFEST_MAGIC { ok = false; }
    if h.version != BADGER_MANIFEST_VERSION { ok = false; }
  }
  let bad_magic = set_at(&m, 0, 88);
  if !err_mh_is(badger_manifest_header_parse(&bad_magic), "badger: manifest bad magic at 0") { ok = false; }
  let bad_ver = set_at(&m, 7, 3);
  if !err_mh_is(badger_manifest_header_parse(&bad_ver), "badger: manifest unsupported version at 4") { ok = false; }
  let short = slice_of(&m, 0, 7);
  if !err_mh_is(badger_manifest_header_parse(&short), "badger: manifest header truncated at 0") { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t17: manifest record framing and replay truncation
// --------------------------------------------------

fn t17() -> TestResult {
  let name = "manifest records: lengths, CRCs, truncated tail";
  var ok = true;
  let m = fx_manifest();
  let rr = badger_manifest_records_parse(&m, 8);
  if !rr.is_ok {
    ok = false;
  } else {
    let r = rr.value;
    if badger_manifest_record_count(&r) != 2 { ok = false; }
    if !int_is(badger_manifest_record_field(&r, 0, BADGER_MANIFEST_RECORD_FIELD_LENGTH), 78) { ok = false; }
    if !int_is(badger_manifest_record_field(&r, 1, BADGER_MANIFEST_RECORD_FIELD_LENGTH), 6) { ok = false; }
    if !int_is(badger_manifest_record_field(&r, 0, BADGER_MANIFEST_RECORD_FIELD_OFFSET), 8) { ok = false; }
    if !int_is(badger_manifest_record_field(&r, 1, BADGER_MANIFEST_RECORD_FIELD_OFFSET), 94) { ok = false; }
    if !int_is(badger_manifest_record_field(&r, 0, BADGER_MANIFEST_RECORD_FIELD_BODY_OFFSET), 16) { ok = false; }
    if !int_is(badger_manifest_record_field(&r, 1, BADGER_MANIFEST_RECORD_FIELD_BODY_OFFSET), 102) { ok = false; }
    if !int_is(badger_manifest_record_field(&r, 0, BADGER_MANIFEST_RECORD_FIELD_CRC), crc_local(&m, 16, 78)) { ok = false; }
    if !int_is(badger_manifest_record_field(&r, 1, BADGER_MANIFEST_RECORD_FIELD_CRC), crc_local(&m, 102, 6)) { ok = false; }
    if r.total_bytes != 100 { ok = false; }
    if r.truncated { ok = false; }
    if r.trunc_offset != 108 { ok = false; }
  }
  let one = slice_of(&m, 0, 105);
  let rr2 = badger_manifest_records_parse(&one, 8);
  if !rr2.is_ok {
    ok = false;
  } else {
    let r2 = rr2.value;
    if badger_manifest_record_count(&r2) != 1 { ok = false; }
    if r2.truncated != true { ok = false; }
    if r2.trunc_offset != 94 { ok = false; }
    if r2.total_bytes != 86 { ok = false; }
  }
  let corrupt = set_at(&m, 20, gb(&m, 20) ^ 255);
  if !err_mrecs_is(badger_manifest_records_parse(&corrupt, 8), "badger: manifest checksum mismatch at 8") { ok = false; }
  let prec = badger_manifest_record_parse(&one, 94);
  if !err_mrec_is(prec, "badger: manifest record truncated at 94") { ok = false; }
  // A fresh upstream manifest: header + one empty change set (length 0,
  // CRC 0), exactly what helpRewrite writes for an empty store.
  var fresh = Vec[UInt8].new();
  fresh.push(66); fresh.push(100); fresh.push(103); fresh.push(114);
  push_be32(&mut fresh, 4);
  push_be32(&mut fresh, 0);
  push_be32(&mut fresh, 0);
  let fr = badger_manifest_records_parse(&fresh, 8);
  if !fr.is_ok {
    ok = false;
  } else {
    let r3 = fr.value;
    // Upstream writes one empty change set (length 0) for a fresh store;
    // ReplayManifestFile reads it as a valid empty record.
    if badger_manifest_record_count(&r3) != 1 { ok = false; }
    if !int_is(badger_manifest_record_field(&r3, 0, BADGER_MANIFEST_RECORD_FIELD_LENGTH), 0) { ok = false; }
    if r3.truncated { ok = false; }
    if r3.trunc_offset != 16 { ok = false; }
  }
  return assert(ok, name);
}

// --------------------------------------------------
//  t18: ManifestChangeSet protobuf parse
// --------------------------------------------------

fn t18() -> TestResult {
  let name = "manifest changesets: protobuf fields and defaults";
  var ok = true;
  let m = fx_manifest();
  let b1 = fx_manifest_body1();
  let cr1 = badger_manifest_changeset_parse(&m, 16, 78);
  if !cr1.is_ok {
    ok = false;
  } else {
    let c = cr1.value;
    if badger_manifest_change_count(&c) != 2 { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 0, BADGER_MANIFEST_CHANGE_FIELD_ID), 1) { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 0, BADGER_MANIFEST_CHANGE_FIELD_OP), BADGER_MANIFEST_OP_CREATE) { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 0, BADGER_MANIFEST_CHANGE_FIELD_LEVEL), 2) { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 0, BADGER_MANIFEST_CHANGE_FIELD_CHECKSUM_SIZE), 32) { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 0, BADGER_MANIFEST_CHANGE_FIELD_CHECKSUM_OFFSET), 24) { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 0, BADGER_MANIFEST_CHANGE_FIELD_OFFSET), 18) { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 0, BADGER_MANIFEST_CHANGE_FIELD_SIZE), 38) { ok = false; }
    if !badger_manifest_change_has_checksum(&c, 0) { ok = false; }
    if gb(&b1, 8) != 0 { ok = false; }
    if gb(&b1, 39) != 31 { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 1, BADGER_MANIFEST_CHANGE_FIELD_ID), 2) { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 1, BADGER_MANIFEST_CHANGE_FIELD_LEVEL), 0) { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 1, BADGER_MANIFEST_CHANGE_FIELD_OFFSET), 58) { ok = false; }
    if !int_is(badger_manifest_change_field(&c, 1, BADGER_MANIFEST_CHANGE_FIELD_CHECKSUM_OFFSET), 62) { ok = false; }
  }
  let b2 = fx_manifest_body2();
  let cr2 = badger_manifest_changeset_parse(&b2, 0, 6);
  if !cr2.is_ok {
    ok = false;
  } else {
    let c2 = cr2.value;
    if badger_manifest_change_count(&c2) != 1 { ok = false; }
    if !int_is(badger_manifest_change_field(&c2, 0, BADGER_MANIFEST_CHANGE_FIELD_ID), 2) { ok = false; }
    if !int_is(badger_manifest_change_field(&c2, 0, BADGER_MANIFEST_CHANGE_FIELD_OP), BADGER_MANIFEST_OP_DELETE) { ok = false; }
    if badger_manifest_change_has_checksum(&c2, 0) { ok = false; }
    if !int_is(badger_manifest_change_field(&c2, 0, BADGER_MANIFEST_CHANGE_FIELD_CHECKSUM_SIZE), 0) { ok = false; }
  }
  // Unknown fields are skipped: prepend field 5 (varint) with value 7.
  var with_unknown = Vec[UInt8].new();
  with_unknown.push(40);
  with_unknown.push(7);
  append_bytes(&mut with_unknown, &b2);
  let cr3 = badger_manifest_changeset_parse(&with_unknown, 0, with_unknown.len());
  if !cr3.is_ok {
    ok = false;
  } else {
    let c3 = cr3.value;
    if badger_manifest_change_count(&c3) != 1 { ok = false; }
    if !int_is(badger_manifest_change_field(&c3, 0, BADGER_MANIFEST_CHANGE_FIELD_ID), 2) { ok = false; }
  }
  if !err_int_is(badger_manifest_change_field(&cr1.value, 2, BADGER_MANIFEST_CHANGE_FIELD_ID), "badger: manifest change index out of range at 2") { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t19: manifest replay (applyChangeSet semantics)
// --------------------------------------------------

fn t19() -> TestResult {
  let name = "manifest replay: create/delete and final table set";
  var ok = true;
  let m = fx_manifest();
  let tr = badger_manifest_replay(&m, 0);
  if !tr.is_ok {
    ok = false;
  } else {
    let t = tr.value;
    if t.record_count != 2 { ok = false; }
    if t.change_count != 3 { ok = false; }
    if t.count != 1 { ok = false; }
    if !int_is(badger_manifest_file_field(&t, 0, BADGER_MANIFEST_TABLE_FIELD_ID), 1) { ok = false; }
    if !int_is(badger_manifest_file_field(&t, 0, BADGER_MANIFEST_TABLE_FIELD_LEVEL), 2) { ok = false; }
    if !int_is(badger_manifest_file_field(&t, 0, BADGER_MANIFEST_TABLE_FIELD_CHECKSUM_SIZE), 32) { ok = false; }
    if !int_is(badger_manifest_file_field(&t, 0, BADGER_MANIFEST_TABLE_FIELD_CHECKSUM_OFFSET), 24) { ok = false; }
    if gb(&m, 24) != 0 { ok = false; }
    if gb(&m, 24 + 31) != 31 { ok = false; }
    if t.truncated { ok = false; }
    if t.trunc_offset != 108 { ok = false; }
  }
  // DELETE of a table that was never created is an error.
  var only_delete = Vec[UInt8].new();
  only_delete.push(66); only_delete.push(100); only_delete.push(103); only_delete.push(114);
  push_be32(&mut only_delete, 4);
  let b2 = fx_manifest_body2();
  push_be32(&mut only_delete, 6);
  push_be32(&mut only_delete, crc_local(&b2, 0, 6));
  append_bytes(&mut only_delete, &b2);
  if !err_mt_is(badger_manifest_replay(&only_delete, 0), "badger: manifest removes non-existing table at 18") { ok = false; }
  // Duplicate CREATE of the same id is an error.
  let b1 = fx_manifest_body1();
  var dup = Vec[UInt8].new();
  dup.push(66); dup.push(100); dup.push(103); dup.push(114);
  push_be32(&mut dup, 4);
  push_be32(&mut dup, 78);
  push_be32(&mut dup, crc_local(&b1, 0, 78));
  append_bytes(&mut dup, &b1);
  push_be32(&mut dup, 78);
  push_be32(&mut dup, crc_local(&b1, 0, 78));
  append_bytes(&mut dup, &b1);
  if !err_mt_is(badger_manifest_replay(&dup, 0), "badger: manifest table exists at 104") { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t20: composite upstream table read end to end
// --------------------------------------------------

fn t20() -> TestResult {
  let name = "composite: upstream table tail -> index -> block -> bloom";
  var ok = true;
  let tbl = fx_table_small();
  if tbl.len() != 237 { ok = false; }
  let tr = badger_sst_tail_parse(&tbl);
  if !tr.is_ok {
    ok = false;
  } else {
    let t = tr.value;
    let ixr = badger_sst_index_parse(&tbl, t.index_offset, t.index_size);
    if !ixr.is_ok {
      ok = false;
    } else {
      let ix = ixr.value;
      let br = badger_sst_index_block_end(&ix, 0);
      if !br.is_ok {
        ok = false;
      } else {
        let block_len: Int = br.value;
        let block = slice_of(&tbl, 0, block_len);
        let wr = badger_sst_block_walk(&block, block_len);
        if !wr.is_ok {
          ok = false;
        } else {
          let w = wr.value;
          if badger_sst_block_count(&w) != 3 { ok = false; }
          let k2 = badger_sst_block_key(&w, 2);
          if !bytes_eq(&k2, &versioned_key("banana", 80)) { ok = false; }
          let vo = badger_sst_block_field(&w, 2, BADGER_SST_FIELD_VALUE_OFFSET);
          let vsv = badger_sst_block_field(&w, 2, BADGER_SST_FIELD_VALUE_SIZE);
          if !vo.is_ok || !vsv.is_ok {
            ok = false;
          } else {
            let vsr = badger_sst_value_struct_decode(&block, vo.value, vsv.value);
            if !vsr.is_ok { ok = false; }
          }
        }
      }
    }
    let bloomr = badger_bloom_parse(&tbl, t.bloom_offset, t.bloom_size);
    if !bloomr.is_ok {
      ok = false;
    } else {
      let apple = text("apple");
      if !bool_is(badger_bloom_has(&apple, &bloomr.value, 0, 5), true) { ok = false; }
    }
  }
  if !str_eq(badger_sst_checksum_hex(&tbl), fx_table_small_sha256()) { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  t21: filename mapping and module metadata
// --------------------------------------------------

fn t21() -> TestResult {
  let name = "sst filenames and module version";
  var ok = true;
  if !str_eq(badger_sst_filename(0), "000000.sst") { ok = false; }
  if !str_eq(badger_sst_filename(1), "000001.sst") { ok = false; }
  if !str_eq(badger_sst_filename(123456), "123456.sst") { ok = false; }
  if !str_eq(badger_sst_filename(1234567), "1234567.sst") { ok = false; }
  if !str_eq(badger_sst_filename(-1), "") { ok = false; }
  if !str_eq(badger_version(), "0.1.0") { ok = false; }
  return assert(ok, name);
}

// --------------------------------------------------
//  main
// --------------------------------------------------

fn main() -> Int {
  io.println("=== xiom.badger conformance tests ===");
  var failed: Int = 0;
  let r1 = t1();
  if r1.passed { io.println("  [PASS] " + r1.name); } else { io.println("  [FAIL] " + r1.name); failed = failed + 1; }
  let r2 = t2();
  if r2.passed { io.println("  [PASS] " + r2.name); } else { io.println("  [FAIL] " + r2.name); failed = failed + 1; }
  let r3 = t3();
  if r3.passed { io.println("  [PASS] " + r3.name); } else { io.println("  [FAIL] " + r3.name); failed = failed + 1; }
  let r4 = t4();
  if r4.passed { io.println("  [PASS] " + r4.name); } else { io.println("  [FAIL] " + r4.name); failed = failed + 1; }
  let r5 = t5();
  if r5.passed { io.println("  [PASS] " + r5.name); } else { io.println("  [FAIL] " + r5.name); failed = failed + 1; }
  let r6 = t6();
  if r6.passed { io.println("  [PASS] " + r6.name); } else { io.println("  [FAIL] " + r6.name); failed = failed + 1; }
  let r7 = t7();
  if r7.passed { io.println("  [PASS] " + r7.name); } else { io.println("  [FAIL] " + r7.name); failed = failed + 1; }
  let r8 = t8();
  if r8.passed { io.println("  [PASS] " + r8.name); } else { io.println("  [FAIL] " + r8.name); failed = failed + 1; }
  let r9 = t9();
  if r9.passed { io.println("  [PASS] " + r9.name); } else { io.println("  [FAIL] " + r9.name); failed = failed + 1; }
  let r10 = t10();
  if r10.passed { io.println("  [PASS] " + r10.name); } else { io.println("  [FAIL] " + r10.name); failed = failed + 1; }
  let r11 = t11();
  if r11.passed { io.println("  [PASS] " + r11.name); } else { io.println("  [FAIL] " + r11.name); failed = failed + 1; }
  let r12 = t12();
  if r12.passed { io.println("  [PASS] " + r12.name); } else { io.println("  [FAIL] " + r12.name); failed = failed + 1; }
  let r13 = t13();
  if r13.passed { io.println("  [PASS] " + r13.name); } else { io.println("  [FAIL] " + r13.name); failed = failed + 1; }
  let r14 = t14();
  if r14.passed { io.println("  [PASS] " + r14.name); } else { io.println("  [FAIL] " + r14.name); failed = failed + 1; }
  let r15 = t15();
  if r15.passed { io.println("  [PASS] " + r15.name); } else { io.println("  [FAIL] " + r15.name); failed = failed + 1; }
  let r16 = t16();
  if r16.passed { io.println("  [PASS] " + r16.name); } else { io.println("  [FAIL] " + r16.name); failed = failed + 1; }
  let r17 = t17();
  if r17.passed { io.println("  [PASS] " + r17.name); } else { io.println("  [FAIL] " + r17.name); failed = failed + 1; }
  let r18 = t18();
  if r18.passed { io.println("  [PASS] " + r18.name); } else { io.println("  [FAIL] " + r18.name); failed = failed + 1; }
  let r19 = t19();
  if r19.passed { io.println("  [PASS] " + r19.name); } else { io.println("  [FAIL] " + r19.name); failed = failed + 1; }
  let r20 = t20();
  if r20.passed { io.println("  [PASS] " + r20.name); } else { io.println("  [FAIL] " + r20.name); failed = failed + 1; }
  let r21 = t21();
  if r21.passed { io.println("  [PASS] " + r21.name); } else { io.println("  [FAIL] " + r21.name); failed = failed + 1; }
  if failed == 0 {
    io.println("xiom.badger: all tests passed");
  } else {
    io.println("xiom.badger: tests failed");
  }
  return failed;
}



