#!/usr/bin/env python3
"""Generate the xiom.jolt vendor tree from an upstream JoltPhysics checkout.

STATUS: STAGED, BLOCKED -- Jolt requires C++17 and the xiom link line passes
no -std flag (clang 22 defaults to C++14), so the generated tree cannot build
through --c-source yet.  This generator was validated against v5.6.0: it
emits 25 per-directory TUs and the whole library compiles under
`-std=c++17` in ~30 s with system clang.  Unblock by adding a
--cxx-standard/extra-args passthrough (or bumping the default); the full
recon + ask are in BINDINGS-SESSION.md (batch 23 relay).

Usage:
  python tools/combine.py <upstream-root> <vendor-dir>

Effects:
  * mirrors <upstream-root>/Jolt/** into <vendor>/Jolt/** verbatim EXCEPT one
    textual transform: `#include <Jolt/...>` becomes `#include "Jolt/..."`.
    The quoted form resolves through the compiler's Microsoft-style include
    stack when a generated TU at the vendor root pulls the file in (the xiom
    link line has no -I passthrough; see SPEC.md section 2).
  * emits one TU per source directory at the vendor root:
    `jolt_tu_<dir-with-underscores>.cpp` includes that directory's .cpp files
    in sorted order.  Splitting per directory keeps same-name statics in
    separate translation units.
  * copies <upstream-root>/LICENSE to <vendor>/LICENSE.
  * prints file/TU counts plus a deterministic sha256 over the generated
    tree (relative paths + bytes) for re-pin diffs.
"""

import hashlib
import os
import re
import shutil
import sys

INCLUDE_RE = re.compile(r'^#include <Jolt/([^>]+)>', re.MULTILINE)
TRANSFORM_EXT = (".h", ".cpp", ".inl")


def transform(text):
    return INCLUDE_RE.sub(lambda m: '#include "Jolt/%s"' % m.group(1), text)


def tree_hash(root, skip):
    h = hashlib.sha256()
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for name in sorted(filenames):
            if name in skip:
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root).replace("\\", "/")
            h.update(rel.encode("utf-8"))
            h.update(b"\0")
            with open(full, "rb") as f:
                h.update(f.read())
    return h.hexdigest()


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    up = os.path.abspath(sys.argv[1])
    vendor = os.path.abspath(sys.argv[2])
    jolt_src = os.path.join(up, "Jolt")
    if not os.path.isdir(jolt_src):
        print("error: no Jolt/ directory under %s" % up)
        return 2

    dst = os.path.join(vendor, "Jolt")
    if os.path.isdir(dst):
        shutil.rmtree(dst)

    file_count = 0
    groups = {}
    for dirpath, dirnames, filenames in os.walk(jolt_src):
        dirnames.sort()
        for name in sorted(filenames):
            src = os.path.join(dirpath, name)
            rel = os.path.relpath(src, jolt_src).replace("\\", "/")
            out = os.path.join(dst, *rel.split("/"))
            os.makedirs(os.path.dirname(out), exist_ok=True)
            with open(src, "rb") as f:
                data = f.read()
            if name.endswith(TRANSFORM_EXT):
                data = transform(data.decode("utf-8")).encode("utf-8")
            with open(out, "wb") as f:
                f.write(data)
            file_count += 1
            if name.endswith(".cpp"):
                group = os.path.dirname(rel).replace("/", "_")
                groups.setdefault(group, []).append("Jolt/" + rel)

    tu_names = []
    for group in sorted(groups):
        members = sorted(groups[group])
        tu_name = "jolt_tu_%s.cpp" % (group if group else "root")
        tu_path = os.path.join(vendor, tu_name)
        with open(tu_path, "w", newline="\n") as f:
            f.write("// GENERATED by tools/combine.py -- do not edit.\n")
            f.write("// TU for Jolt/%s (%d sources).\n\n" % (group.replace("_", "/"), len(members)))
            for member in members:
                f.write('#include "%s"\n' % member)
        tu_names.append(tu_name)

    license_src = os.path.join(up, "LICENSE")
    if os.path.isfile(license_src):
        shutil.copyfile(license_src, os.path.join(vendor, "LICENSE"))

    print("vendored files: %d" % file_count)
    print("generated TUs:  %d (%s)" % (len(tu_names), ", ".join(tu_names)))
    print("tree sha256 (generated, LICENSE excluded): %s" % tree_hash(vendor, {"LICENSE"}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
