# ============================================================================
# export-namespaces.ps1 -- snapshot every package/module name for the stdlib
# cross-check.
#
# Writes docs/PACKAGE-NAMESPACES.txt: the canonical list of dotted package
# names plus every module namespace declared by this repo's packages. The
# stdlib session reads the snapshot (its side of the two-way uniqueness
# check); the packages side checks the stdlib via scripts/namespace-check.ps1.
#
# Regenerate at every wave wrap after manifest changes.
#
# Usage:
#   .\scripts\export-namespaces.ps1
#   .\scripts\export-namespaces.ps1 -Out docs\PACKAGE-NAMESPACES.txt
# ============================================================================
[CmdletBinding()]
param(
    [string]$Out = ""
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $Out) { $Out = Join-Path $repoRoot "docs\PACKAGE-NAMESPACES.txt" }
$packagesDir = Join-Path $repoRoot "packages"

$names = New-Object System.Collections.Generic.HashSet[string]
$modules = New-Object System.Collections.Generic.HashSet[string]
$count = 0

foreach ($dir in (Get-ChildItem -LiteralPath $packagesDir -Directory | Sort-Object Name)) {
    $manifest = Join-Path $dir.FullName "package.xi"
    if (-not (Test-Path -LiteralPath $manifest)) { continue }
    $count++
    $content = Get-Content -LiteralPath $manifest -Raw
    $m = [regex]::Match($content, 'name\s*:\s*"([^"]+)"')
    if ($m.Success) { [void]$names.Add($m.Groups[1].Value) }
    $mm = [regex]::Match($content, 'modules\s*:\s*\[([^\]]*)\]')
    if ($mm.Success) {
        foreach ($q in ([regex]::Matches($mm.Groups[1].Value, '"([^"]+)"'))) {
            [void]$modules.Add($q.Groups[1].Value)
        }
    }
    # Module declarations are the ground truth for the module list.
    $srcDir = Join-Path $dir.FullName "src"
    if (Test-Path -LiteralPath $srcDir) {
        foreach ($file in (Get-ChildItem -LiteralPath $srcDir -Recurse -Filter *.xi -File)) {
            $decl = [regex]::Match((Get-Content -LiteralPath $file.FullName -Raw),
                '(?m)^\s*module\s+([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)')
            if ($decl.Success) { [void]$modules.Add($decl.Groups[1].Value) }
        }
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# XIOM packages namespace snapshot (generated by scripts/export-namespaces.ps1)")
$lines.Add("# Regenerate at every wave wrap; the stdlib session cross-checks new")
$lines.Add("# module names against this list (packages check the stdlib via")
$lines.Add("# scripts/namespace-check.ps1).")
$lines.Add("# generated: $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssK')")
$lines.Add("# packages: $($names.Count)  modules: $($modules.Count)")
$lines.Add("")
$lines.Add("## package names")
foreach ($n in ($names | Sort-Object)) { $lines.Add($n) }
$lines.Add("")
$lines.Add("## module namespaces")
foreach ($n in ($modules | Sort-Object)) { $lines.Add($n) }
$lines.Add("")

Set-Content -LiteralPath $Out -Value ($lines -join "`r`n") -Encoding ASCII
Write-Output "export-namespaces: $($names.Count) package name(s), $($modules.Count) module(s) -> $Out"
