#!/usr/bin/env python3
"""Embed tests/fixtures/BlenderDefault_248.blend as a C byte array.

The .blend format is DNA-driven binary and cannot be synthesized in-memory
like the OBJ/PLY/glTF2/COLLADA/FBX probes, so the BLEND probe imports this
committed fixture (Blender 2.48 default scene: one cube; assimp's loader
emits 6 quad faces with 24 unshared loop-vertices).

The fixture is the upstream assimp v6.0.5 file
`test/models/BLEND/BlenderDefault_248.blend` (the repository's
BSD-3-Clause test-model set; fetched from the pinned commit
392a658f9c271be965271f45e7521a1b80ea4392).

Regenerate this .inc (from the package directory) after changing the
fixture:

    python tools/embed_blend_fixture.py
"""
import hashlib
import os

PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(PKG, "tests", "fixtures", "BlenderDefault_248.blend")
DST = os.path.join(PKG, "src", "blend_default_248.inc")


def main():
    with open(SRC, "rb") as f:
        data = f.read()
    digest = hashlib.sha256(data).hexdigest()
    lines = [
        "// Generated by tools/embed_blend_fixture.py -- DO NOT EDIT.",
        "// Source fixture: tests/fixtures/BlenderDefault_248.blend",
        "// Provenance: assimp v6.0.5 test/models/BLEND/BlenderDefault_248.blend",
        "// (BSD-3-Clause repo; Blender 2.48 default scene: one cube).",
        "// sha256: %s (%d bytes)" % (digest, len(data)),
        "static const unsigned char kBlendDefault248[] = {",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("  " + " ".join("0x%02x," % b for b in chunk))
    lines.append("};")
    lines.append("static const unsigned int kBlendDefault248Len = %d;" % len(data))
    lines.append("")
    with open(DST, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d bytes source, %d bytes fixture)"
          % (DST, os.path.getsize(DST), len(data)))


if __name__ == "__main__":
    main()
