#include "xvk_bridge.h"

#include "xvk_util.c"
#include "xvk_math.c"
#include "xvk_instance.c"
#include "xvk_swapchain.c"
#include "xvk_pipeline.c"
#include "xvk_renderpass.c"
#include "xvk_descriptor.c"
#include "xvk_buffer.c"
#include "xvk_command.c"
#include "xvk_query.c"
#include "xvk_legacy.c"
#include "xvk_offscreen.c"
#include "xvk_frame.c"
#include "xvk_app.c"
